language: go

go:
  - 1.13.x
  - master

os:
  - linux
  - osx

addons:
  apt:
    update: true
    install: protobuf-compiler
  chrome: stable

install:
  - go get -u github.com/uber/prototool@v1.9.0

script:
  - echo $PATH
  - ls $GOBIN
  - make dist
