language: go

go:
  - 1.13.x
  - master

os:
  - linux
  - osx

addons:
  apt:
    update: true
  chrome: stable

before_install:
  - sudo apt-get -y install protobuf-compiler
  - go install github.com/uber/prototool@v1.9.0

script:
  - make dist
