language: go

go:
  - 1.13.x
  - master

os:
  - linux
  - osx

addons:
  apt:
    update: true
    install: protobuf-compiler
  chrome: stable

before_install:
  - go get github.com/uber/prototool@v1.9.0

install:
  - export GOBIN="$(go env GOPATH)/bin"
  - export PATH="$PATH:$GOBIN"
  - go version
  - go env 

script:
  - make dist
