language: go

go:
  - 1.13.x
  - master
go_import_path: github.com/vsekhar/protoweb

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: master

addons:
  apt:
    update: true
    install: protobuf-compiler
#  chrome: stable # not needed unless capturing new set of headers

install:
  - go get github.com/uber/prototool/cmd/prototool

script:
  - make dist
