// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mime.proto

package web

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Common_MIME_Types int32

const (
	Common_MIME_Types_COMMON_MIME_TYPE_UNUSED Common_MIME_Types = 0
)

var Common_MIME_Types_name = map[int32]string{
	0: "COMMON_MIME_TYPE_UNUSED",
}

var Common_MIME_Types_value = map[string]int32{
	"COMMON_MIME_TYPE_UNUSED": 0,
}

func (x Common_MIME_Types) String() string {
	return proto.EnumName(Common_MIME_Types_name, int32(x))
}

func (Common_MIME_Types) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1e03494e12603071, []int{0}
}

// TODO: Do common MIME types appear here? Always? Only if promoted? Never (no).
type MIME_Types int32

const (
	MIME_Types_MIME_TYPE_UNUSED MIME_Types = 0
)

var MIME_Types_name = map[int32]string{
	0: "MIME_TYPE_UNUSED",
}

var MIME_Types_value = map[string]int32{
	"MIME_TYPE_UNUSED": 0,
}

func (x MIME_Types) String() string {
	return proto.EnumName(MIME_Types_name, int32(x))
}

func (MIME_Types) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1e03494e12603071, []int{1}
}

type MIME_Type struct {
	// Types that are valid to be assigned to MIME_Type:
	//	*MIME_Type_Common
	//	*MIME_Type_Uncommon
	MIME_Type            isMIME_Type_MIME_Type `protobuf_oneof:"MIME_Type"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MIME_Type) Reset()         { *m = MIME_Type{} }
func (m *MIME_Type) String() string { return proto.CompactTextString(m) }
func (*MIME_Type) ProtoMessage()    {}
func (*MIME_Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e03494e12603071, []int{0}
}

func (m *MIME_Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MIME_Type.Unmarshal(m, b)
}
func (m *MIME_Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MIME_Type.Marshal(b, m, deterministic)
}
func (m *MIME_Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MIME_Type.Merge(m, src)
}
func (m *MIME_Type) XXX_Size() int {
	return xxx_messageInfo_MIME_Type.Size(m)
}
func (m *MIME_Type) XXX_DiscardUnknown() {
	xxx_messageInfo_MIME_Type.DiscardUnknown(m)
}

var xxx_messageInfo_MIME_Type proto.InternalMessageInfo

type isMIME_Type_MIME_Type interface {
	isMIME_Type_MIME_Type()
}

type MIME_Type_Common struct {
	Common Common_MIME_Types `protobuf:"varint,1,opt,name=Common,proto3,enum=web.Common_MIME_Types,oneof"`
}

type MIME_Type_Uncommon struct {
	Uncommon MIME_Types `protobuf:"varint,2,opt,name=Uncommon,proto3,enum=web.MIME_Types,oneof"`
}

func (*MIME_Type_Common) isMIME_Type_MIME_Type() {}

func (*MIME_Type_Uncommon) isMIME_Type_MIME_Type() {}

func (m *MIME_Type) GetMIME_Type() isMIME_Type_MIME_Type {
	if m != nil {
		return m.MIME_Type
	}
	return nil
}

func (m *MIME_Type) GetCommon() Common_MIME_Types {
	if x, ok := m.GetMIME_Type().(*MIME_Type_Common); ok {
		return x.Common
	}
	return Common_MIME_Types_COMMON_MIME_TYPE_UNUSED
}

func (m *MIME_Type) GetUncommon() MIME_Types {
	if x, ok := m.GetMIME_Type().(*MIME_Type_Uncommon); ok {
		return x.Uncommon
	}
	return MIME_Types_MIME_TYPE_UNUSED
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MIME_Type) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MIME_Type_Common)(nil),
		(*MIME_Type_Uncommon)(nil),
	}
}

func init() {
	proto.RegisterEnum("web.Common_MIME_Types", Common_MIME_Types_name, Common_MIME_Types_value)
	proto.RegisterEnum("web.MIME_Types", MIME_Types_name, MIME_Types_value)
	proto.RegisterType((*MIME_Type)(nil), "web.MIME_Type")
}

func init() { proto.RegisterFile("mime.proto", fileDescriptor_1e03494e12603071) }

var fileDescriptor_1e03494e12603071 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcd, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x4f, 0x4d, 0x52, 0xaa, 0xe4, 0xe2, 0xf4,
	0xf5, 0xf4, 0x75, 0x8d, 0x0f, 0xa9, 0x2c, 0x48, 0x15, 0x32, 0xe0, 0x62, 0x73, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0x12, 0xd3, 0x2b, 0x4f, 0x4d, 0xd2, 0x83,
	0x08, 0xc5, 0xc3, 0x95, 0x15, 0x7b, 0x30, 0x04, 0x41, 0xd5, 0x09, 0xe9, 0x72, 0x71, 0x84, 0xe6,
	0x25, 0x43, 0xf4, 0x30, 0x81, 0xf5, 0xf0, 0x83, 0xf5, 0xa0, 0x28, 0x86, 0x2b, 0x71, 0xe2, 0x46,
	0xb2, 0x4d, 0xcb, 0x80, 0x4b, 0x10, 0xc3, 0x68, 0x21, 0x69, 0x2e, 0x71, 0x67, 0x7f, 0x5f, 0x5f,
	0x7f, 0x3f, 0xa8, 0x60, 0x64, 0x80, 0x6b, 0x7c, 0xa8, 0x5f, 0x68, 0xb0, 0xab, 0x8b, 0x00, 0x83,
	0x96, 0x12, 0x17, 0x17, 0x92, 0x52, 0x11, 0x2e, 0x01, 0x4c, 0x35, 0x49, 0x6c, 0x60, 0xcf, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x60, 0xcf, 0xb3, 0x52, 0xea, 0x00, 0x00, 0x00,
}
