// Code generated by protoc-gen-go. DO NOT EDIT.
// source: util.proto

package web

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Wildcard is a directive for use inside a oneof.
//
// NB: The oneof handles the unspecified case (when populated by
// one of the other values) so we don't need a *_UNSPECIFIED=0
// value.
// Wildcard is a directive for use inside a oneof.
//
// NB: The oneof handles the unspecified case (when populated by
// one of the other values) so we don't need a *_UNSPECIFIED=0
// value.
type Wildcard int32

const (
	Wildcard_STAR Wildcard = 0
)

var Wildcard_name = map[int32]string{
	0: "STAR",
}

var Wildcard_value = map[string]int32{
	"STAR": 0,
}

func (x Wildcard) String() string {
	return proto.EnumName(Wildcard_name, int32(x))
}

func (Wildcard) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_170ba741606d8a4c, []int{0}
}

// Already is a directive for use inside a oneof.
//
// NB: The oneof handles the unspecified case (when populated by
// one of the other values) so we don't need a *_UNSPECIFIED=0
// value.
type Already int32

const (
	Already_ALREADY Already = 0
)

var Already_name = map[int32]string{
	0: "ALREADY",
}

var Already_value = map[string]int32{
	"ALREADY": 0,
}

func (x Already) String() string {
	return proto.EnumName(Already_name, int32(x))
}

func (Already) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_170ba741606d8a4c, []int{1}
}

// Clear is a directive for use inside a oneof.
//
// NB: The oneof handles the unspecified case (when populated by
// one of the other values) so we don't need a *_UNSPECIFIED=0
// value.
type Clear int32

const (
	Clear_CLEAR Clear = 0
)

var Clear_name = map[int32]string{
	0: "CLEAR",
}

var Clear_value = map[string]int32{
	"CLEAR": 0,
}

func (x Clear) String() string {
	return proto.EnumName(Clear_name, int32(x))
}

func (Clear) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_170ba741606d8a4c, []int{2}
}

// StringList is used when a list of strings is needed inside
// a oneof, since oneof's don't support repeated fields.
type StringList struct {
	Strings              []string `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringList) Reset()         { *m = StringList{} }
func (m *StringList) String() string { return proto.CompactTextString(m) }
func (*StringList) ProtoMessage()    {}
func (*StringList) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ba741606d8a4c, []int{0}
}

func (m *StringList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringList.Unmarshal(m, b)
}
func (m *StringList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringList.Marshal(b, m, deterministic)
}
func (m *StringList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringList.Merge(m, src)
}
func (m *StringList) XXX_Size() int {
	return xxx_messageInfo_StringList.Size(m)
}
func (m *StringList) XXX_DiscardUnknown() {
	xxx_messageInfo_StringList.DiscardUnknown(m)
}

var xxx_messageInfo_StringList proto.InternalMessageInfo

func (m *StringList) GetStrings() []string {
	if m != nil {
		return m.Strings
	}
	return nil
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_170ba741606d8a4c, []int{1}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("web.Wildcard", Wildcard_name, Wildcard_value)
	proto.RegisterEnum("web.Already", Already_name, Already_value)
	proto.RegisterEnum("web.Clear", Clear_name, Clear_value)
	proto.RegisterType((*StringList)(nil), "web.StringList")
	proto.RegisterType((*KeyValue)(nil), "web.KeyValue")
}

func init() { proto.RegisterFile("util.proto", fileDescriptor_170ba741606d8a4c) }

var fileDescriptor_170ba741606d8a4c = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0xc9, 0xcc,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x4f, 0x4d, 0x52, 0x52, 0xe3, 0xe2, 0x0a,
	0x2e, 0x29, 0xca, 0xcc, 0x4b, 0xf7, 0xc9, 0x2c, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0x2f, 0x06, 0xf3,
	0x8a, 0x25, 0x18, 0x15, 0x98, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x25, 0x23, 0x2e, 0x0e, 0xef, 0xd4,
	0xca, 0xb0, 0xc4, 0x9c, 0xd2, 0x54, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x10, 0x53, 0x48, 0x84, 0x8b, 0xb5, 0x0c, 0x24, 0x25, 0xc1, 0x04, 0x16,
	0x83, 0x70, 0xb4, 0x44, 0xb8, 0x38, 0xc2, 0x33, 0x73, 0x52, 0x92, 0x13, 0x8b, 0x52, 0x84, 0x38,
	0xb8, 0x58, 0x82, 0x43, 0x1c, 0x83, 0x04, 0x18, 0xb4, 0xc4, 0xb8, 0xd8, 0x1d, 0x73, 0x8a, 0x52,
	0x13, 0x53, 0x2a, 0x85, 0xb8, 0xb9, 0xd8, 0x1d, 0x7d, 0x82, 0x5c, 0x1d, 0x5d, 0x22, 0x05, 0x18,
	0xb4, 0x84, 0xb8, 0x58, 0x9d, 0x73, 0x52, 0x13, 0x8b, 0x84, 0x38, 0xb9, 0x58, 0x9d, 0x7d, 0x5c,
	0x41, 0x6a, 0x93, 0xd8, 0xc0, 0x2e, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x44, 0xfc, 0x89,
	0x24, 0xb7, 0x00, 0x00, 0x00,
}
