// Code generated by protoc-gen-go. DO NOT EDIT.
// source: web.proto

package web

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Encodings int32

const (
	Encodings_ENCODINGS_UNSPECIFIED Encodings = 0
	Encodings_IDENTITY              Encodings = 1
	Encodings_GZIP                  Encodings = 2
	Encodings_COMPRESS              Encodings = 3
	Encodings_DEFLATE               Encodings = 4
	Encodings_BR                    Encodings = 5
)

var Encodings_name = map[int32]string{
	0: "ENCODINGS_UNSPECIFIED",
	1: "IDENTITY",
	2: "GZIP",
	3: "COMPRESS",
	4: "DEFLATE",
	5: "BR",
}

var Encodings_value = map[string]int32{
	"ENCODINGS_UNSPECIFIED": 0,
	"IDENTITY":              1,
	"GZIP":                  2,
	"COMPRESS":              3,
	"DEFLATE":               4,
	"BR":                    5,
}

func (x Encodings) String() string {
	return proto.EnumName(Encodings_name, int32(x))
}

func (Encodings) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{0}
}

type CacheControlResponse_Directives int32

const (
	CacheControlResponse_UNUSED_DIRECTIVE CacheControlResponse_Directives = 0
	CacheControlResponse_MUST_REVALIDATE  CacheControlResponse_Directives = 1
	CacheControlResponse_NO_CACHE         CacheControlResponse_Directives = 2
	CacheControlResponse_NO_STORE         CacheControlResponse_Directives = 3
	CacheControlResponse_NO_TRANSFORM     CacheControlResponse_Directives = 4
	CacheControlResponse_PUBLIC           CacheControlResponse_Directives = 5
	CacheControlResponse_PRIVATE          CacheControlResponse_Directives = 6
	CacheControlResponse_PROXY_REVALIDATE CacheControlResponse_Directives = 7
	CacheControlResponse_MAX_AGE          CacheControlResponse_Directives = 8
	CacheControlResponse_S_MAXAGE         CacheControlResponse_Directives = 9
)

var CacheControlResponse_Directives_name = map[int32]string{
	0: "UNUSED_DIRECTIVE",
	1: "MUST_REVALIDATE",
	2: "NO_CACHE",
	3: "NO_STORE",
	4: "NO_TRANSFORM",
	5: "PUBLIC",
	6: "PRIVATE",
	7: "PROXY_REVALIDATE",
	8: "MAX_AGE",
	9: "S_MAXAGE",
}

var CacheControlResponse_Directives_value = map[string]int32{
	"UNUSED_DIRECTIVE": 0,
	"MUST_REVALIDATE":  1,
	"NO_CACHE":         2,
	"NO_STORE":         3,
	"NO_TRANSFORM":     4,
	"PUBLIC":           5,
	"PRIVATE":          6,
	"PROXY_REVALIDATE": 7,
	"MAX_AGE":          8,
	"S_MAXAGE":         9,
}

func (x CacheControlResponse_Directives) String() string {
	return proto.EnumName(CacheControlResponse_Directives_name, int32(x))
}

func (CacheControlResponse_Directives) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{1, 0}
}

type Response_Headers_AccessControlAllowCredentialsValue int32

const (
	Response_Headers_UNUSED_ACCESS_CONTROL_ALLOW_CREDENTIALS_VALUE Response_Headers_AccessControlAllowCredentialsValue = 0
	Response_Headers_FALSE                                         Response_Headers_AccessControlAllowCredentialsValue = 1
	Response_Headers_TRUE                                          Response_Headers_AccessControlAllowCredentialsValue = 2
)

var Response_Headers_AccessControlAllowCredentialsValue_name = map[int32]string{
	0: "UNUSED_ACCESS_CONTROL_ALLOW_CREDENTIALS_VALUE",
	1: "FALSE",
	2: "TRUE",
}

var Response_Headers_AccessControlAllowCredentialsValue_value = map[string]int32{
	"UNUSED_ACCESS_CONTROL_ALLOW_CREDENTIALS_VALUE": 0,
	"FALSE": 1,
	"TRUE":  2,
}

func (x Response_Headers_AccessControlAllowCredentialsValue) String() string {
	return proto.EnumName(Response_Headers_AccessControlAllowCredentialsValue_name, int32(x))
}

func (Response_Headers_AccessControlAllowCredentialsValue) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{3, 0, 0}
}

type Response_Headers_XFrameOptionsValue int32

const (
	Response_Headers_UNUSED_X_FRAME_OPTIONS_VALUE Response_Headers_XFrameOptionsValue = 0
	Response_Headers_DENY                         Response_Headers_XFrameOptionsValue = 1
	Response_Headers_SAMEORIGIN                   Response_Headers_XFrameOptionsValue = 2
)

var Response_Headers_XFrameOptionsValue_name = map[int32]string{
	0: "UNUSED_X_FRAME_OPTIONS_VALUE",
	1: "DENY",
	2: "SAMEORIGIN",
}

var Response_Headers_XFrameOptionsValue_value = map[string]int32{
	"UNUSED_X_FRAME_OPTIONS_VALUE": 0,
	"DENY":                         1,
	"SAMEORIGIN":                   2,
}

func (x Response_Headers_XFrameOptionsValue) String() string {
	return proto.EnumName(Response_Headers_XFrameOptionsValue_name, int32(x))
}

func (Response_Headers_XFrameOptionsValue) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{3, 0, 1}
}

type Response_Headers_SetCookieMessage_SameSiteValue int32

const (
	Response_Headers_SetCookieMessage_UNUSED_SAMESITE_VALUE Response_Headers_SetCookieMessage_SameSiteValue = 0
	Response_Headers_SetCookieMessage_STRICT                Response_Headers_SetCookieMessage_SameSiteValue = 1
	Response_Headers_SetCookieMessage_LAX                   Response_Headers_SetCookieMessage_SameSiteValue = 2
	Response_Headers_SetCookieMessage_NONE                  Response_Headers_SetCookieMessage_SameSiteValue = 3
)

var Response_Headers_SetCookieMessage_SameSiteValue_name = map[int32]string{
	0: "UNUSED_SAMESITE_VALUE",
	1: "STRICT",
	2: "LAX",
	3: "NONE",
}

var Response_Headers_SetCookieMessage_SameSiteValue_value = map[string]int32{
	"UNUSED_SAMESITE_VALUE": 0,
	"STRICT":                1,
	"LAX":                   2,
	"NONE":                  3,
}

func (x Response_Headers_SetCookieMessage_SameSiteValue) String() string {
	return proto.EnumName(Response_Headers_SetCookieMessage_SameSiteValue_name, int32(x))
}

func (Response_Headers_SetCookieMessage_SameSiteValue) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{3, 0, 1, 0}
}

// StringList is used when a list of strings is needed inside
// a oneof, since oneof's don't support repeated fields.
type StringList struct {
	Strings              []string `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringList) Reset()         { *m = StringList{} }
func (m *StringList) String() string { return proto.CompactTextString(m) }
func (*StringList) ProtoMessage()    {}
func (*StringList) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{0}
}

func (m *StringList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringList.Unmarshal(m, b)
}
func (m *StringList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringList.Marshal(b, m, deterministic)
}
func (m *StringList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringList.Merge(m, src)
}
func (m *StringList) XXX_Size() int {
	return xxx_messageInfo_StringList.Size(m)
}
func (m *StringList) XXX_DiscardUnknown() {
	xxx_messageInfo_StringList.DiscardUnknown(m)
}

var xxx_messageInfo_StringList proto.InternalMessageInfo

func (m *StringList) GetStrings() []string {
	if m != nil {
		return m.Strings
	}
	return nil
}

type CacheControlResponse struct {
	Directive            CacheControlResponse_Directives `protobuf:"varint,1,opt,name=directive,proto3,enum=web.CacheControlResponse_Directives" json:"directive,omitempty"`
	Seconds              uint64                          `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *CacheControlResponse) Reset()         { *m = CacheControlResponse{} }
func (m *CacheControlResponse) String() string { return proto.CompactTextString(m) }
func (*CacheControlResponse) ProtoMessage()    {}
func (*CacheControlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{1}
}

func (m *CacheControlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheControlResponse.Unmarshal(m, b)
}
func (m *CacheControlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheControlResponse.Marshal(b, m, deterministic)
}
func (m *CacheControlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheControlResponse.Merge(m, src)
}
func (m *CacheControlResponse) XXX_Size() int {
	return xxx_messageInfo_CacheControlResponse.Size(m)
}
func (m *CacheControlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheControlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CacheControlResponse proto.InternalMessageInfo

func (m *CacheControlResponse) GetDirective() CacheControlResponse_Directives {
	if m != nil {
		return m.Directive
	}
	return CacheControlResponse_UNUSED_DIRECTIVE
}

func (m *CacheControlResponse) GetSeconds() uint64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

type Request struct {
	Method Method `protobuf:"varint,1,opt,name=method,proto3,enum=web.Method" json:"method,omitempty"`
	// TODO: separate absolute vs. relative?
	//
	// Types that are valid to be assigned to URI:
	//	*Request_UriWildcard
	//	*Request_UriString
	URI                  isRequest_URI   `protobuf_oneof:"URI"`
	Query                []*KeyValue     `protobuf:"bytes,4,rep,name=query,proto3" json:"query,omitempty"`
	Header               *RequestHeaders `protobuf:"bytes,5,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMethod() Method {
	if m != nil {
		return m.Method
	}
	return Method_UNUSED_METHOD
}

type isRequest_URI interface {
	isRequest_URI()
}

type Request_UriWildcard struct {
	UriWildcard Wildcard `protobuf:"varint,2,opt,name=uri_wildcard,json=uriWildcard,proto3,enum=web.Wildcard,oneof"`
}

type Request_UriString struct {
	UriString string `protobuf:"bytes,3,opt,name=uri_string,json=uriString,proto3,oneof"`
}

func (*Request_UriWildcard) isRequest_URI() {}

func (*Request_UriString) isRequest_URI() {}

func (m *Request) GetURI() isRequest_URI {
	if m != nil {
		return m.URI
	}
	return nil
}

func (m *Request) GetUriWildcard() Wildcard {
	if x, ok := m.GetURI().(*Request_UriWildcard); ok {
		return x.UriWildcard
	}
	return Wildcard_STAR
}

func (m *Request) GetUriString() string {
	if x, ok := m.GetURI().(*Request_UriString); ok {
		return x.UriString
	}
	return ""
}

func (m *Request) GetQuery() []*KeyValue {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *Request) GetHeader() *RequestHeaders {
	if m != nil {
		return m.Header
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Request) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Request_UriWildcard)(nil),
		(*Request_UriString)(nil),
	}
}

type Response struct {
	Status StatusCodes `protobuf:"varint,1,opt,name=status,proto3,enum=web.StatusCodes" json:"status,omitempty"`
	// message Headers
	Header               *Response_Headers `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Body                 []byte            `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() StatusCodes {
	if m != nil {
		return m.Status
	}
	return StatusCodes_STATUS_CODE_UNUSED
}

func (m *Response) GetHeader() *Response_Headers {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response_Headers struct {
	// Types that are valid to be assigned to AccessControlAllowOrigin:
	//	*Response_Headers_AccessControlAllowOriginAll
	//	*Response_Headers_AccessControlAllowOriginOrigins
	AccessControlAllowOrigin      isResponse_Headers_AccessControlAllowOrigin         `protobuf_oneof:"AccessControlAllowOrigin"`
	AccessControlAllowCredentials Response_Headers_AccessControlAllowCredentialsValue `protobuf:"varint,3,opt,name=access_control_allow_credentials,json=accessControlAllowCredentials,proto3,enum=web.Response_Headers_AccessControlAllowCredentialsValue" json:"access_control_allow_credentials,omitempty"`
	AccessControlExposeHeaders    []string                                            `protobuf:"bytes,4,rep,name=access_control_expose_headers,json=accessControlExposeHeaders,proto3" json:"access_control_expose_headers,omitempty"`
	// Types that are valid to be assigned to Alt_Svc:
	//	*Response_Headers_AltSvcClear
	//	*Response_Headers_Service
	Alt_Svc      isResponse_Headers_Alt_Svc `protobuf_oneof:"Alt_Svc"`
	CacheControl *CacheControlResponse      `protobuf:"bytes,18,opt,name=cache_control,json=cacheControl,proto3" json:"cache_control,omitempty"`
	ContentType  *MIMEType                  `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Date         *timestamp.Timestamp       `protobuf:"bytes,8,opt,name=date,proto3" json:"date,omitempty"`
	// Types that are valid to be assigned to Expires:
	//	*Response_Headers_ExpiresAlready
	//	*Response_Headers_ExpiresDate
	Expires isResponse_Headers_Expires `protobuf_oneof:"Expires"`
	Server  string                     `protobuf:"bytes,11,opt,name=server,proto3" json:"server,omitempty"`
	// Types that are valid to be assigned to Vary:
	//	*Response_Headers_VaryAll
	//	*Response_Headers_VaryHeaders
	Vary                 isResponse_Headers_Vary              `protobuf_oneof:"Vary"`
	XFrameOptions        Response_Headers_XFrameOptionsValue  `protobuf:"varint,16,opt,name=x_frame_options,json=xFrameOptions,proto3,enum=web.Response_Headers_XFrameOptionsValue" json:"x_frame_options,omitempty"`
	XXssProtection       string                               `protobuf:"bytes,15,opt,name=x_xss_protection,json=xXssProtection,proto3" json:"x_xss_protection,omitempty"`
	SetCookie            []*Response_Headers_SetCookieMessage `protobuf:"bytes,14,rep,name=set_cookie,json=setCookie,proto3" json:"set_cookie,omitempty"`
	Other                []*KeyValue                          `protobuf:"bytes,17,rep,name=other,proto3" json:"other,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *Response_Headers) Reset()         { *m = Response_Headers{} }
func (m *Response_Headers) String() string { return proto.CompactTextString(m) }
func (*Response_Headers) ProtoMessage()    {}
func (*Response_Headers) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{3, 0}
}

func (m *Response_Headers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Headers.Unmarshal(m, b)
}
func (m *Response_Headers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Headers.Marshal(b, m, deterministic)
}
func (m *Response_Headers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Headers.Merge(m, src)
}
func (m *Response_Headers) XXX_Size() int {
	return xxx_messageInfo_Response_Headers.Size(m)
}
func (m *Response_Headers) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Headers.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Headers proto.InternalMessageInfo

type isResponse_Headers_AccessControlAllowOrigin interface {
	isResponse_Headers_AccessControlAllowOrigin()
}

type Response_Headers_AccessControlAllowOriginAll struct {
	AccessControlAllowOriginAll Wildcard `protobuf:"varint,1,opt,name=access_control_allow_origin_all,json=accessControlAllowOriginAll,proto3,enum=web.Wildcard,oneof"`
}

type Response_Headers_AccessControlAllowOriginOrigins struct {
	AccessControlAllowOriginOrigins *StringList `protobuf:"bytes,2,opt,name=access_control_allow_origin_origins,json=accessControlAllowOriginOrigins,proto3,oneof"`
}

func (*Response_Headers_AccessControlAllowOriginAll) isResponse_Headers_AccessControlAllowOrigin() {}

func (*Response_Headers_AccessControlAllowOriginOrigins) isResponse_Headers_AccessControlAllowOrigin() {
}

func (m *Response_Headers) GetAccessControlAllowOrigin() isResponse_Headers_AccessControlAllowOrigin {
	if m != nil {
		return m.AccessControlAllowOrigin
	}
	return nil
}

func (m *Response_Headers) GetAccessControlAllowOriginAll() Wildcard {
	if x, ok := m.GetAccessControlAllowOrigin().(*Response_Headers_AccessControlAllowOriginAll); ok {
		return x.AccessControlAllowOriginAll
	}
	return Wildcard_STAR
}

func (m *Response_Headers) GetAccessControlAllowOriginOrigins() *StringList {
	if x, ok := m.GetAccessControlAllowOrigin().(*Response_Headers_AccessControlAllowOriginOrigins); ok {
		return x.AccessControlAllowOriginOrigins
	}
	return nil
}

func (m *Response_Headers) GetAccessControlAllowCredentials() Response_Headers_AccessControlAllowCredentialsValue {
	if m != nil {
		return m.AccessControlAllowCredentials
	}
	return Response_Headers_UNUSED_ACCESS_CONTROL_ALLOW_CREDENTIALS_VALUE
}

func (m *Response_Headers) GetAccessControlExposeHeaders() []string {
	if m != nil {
		return m.AccessControlExposeHeaders
	}
	return nil
}

type isResponse_Headers_Alt_Svc interface {
	isResponse_Headers_Alt_Svc()
}

type Response_Headers_AltSvcClear struct {
	AltSvcClear Clear `protobuf:"varint,5,opt,name=alt_svc_clear,json=altSvcClear,proto3,enum=web.Clear,oneof"`
}

type Response_Headers_Service struct {
	Service *Response_Headers_AltSvcMessage `protobuf:"bytes,6,opt,name=service,proto3,oneof"`
}

func (*Response_Headers_AltSvcClear) isResponse_Headers_Alt_Svc() {}

func (*Response_Headers_Service) isResponse_Headers_Alt_Svc() {}

func (m *Response_Headers) GetAlt_Svc() isResponse_Headers_Alt_Svc {
	if m != nil {
		return m.Alt_Svc
	}
	return nil
}

func (m *Response_Headers) GetAltSvcClear() Clear {
	if x, ok := m.GetAlt_Svc().(*Response_Headers_AltSvcClear); ok {
		return x.AltSvcClear
	}
	return Clear_CLEAR
}

func (m *Response_Headers) GetService() *Response_Headers_AltSvcMessage {
	if x, ok := m.GetAlt_Svc().(*Response_Headers_Service); ok {
		return x.Service
	}
	return nil
}

func (m *Response_Headers) GetCacheControl() *CacheControlResponse {
	if m != nil {
		return m.CacheControl
	}
	return nil
}

func (m *Response_Headers) GetContentType() *MIMEType {
	if m != nil {
		return m.ContentType
	}
	return nil
}

func (m *Response_Headers) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

type isResponse_Headers_Expires interface {
	isResponse_Headers_Expires()
}

type Response_Headers_ExpiresAlready struct {
	ExpiresAlready Already `protobuf:"varint,9,opt,name=expires_already,json=expiresAlready,proto3,enum=web.Already,oneof"`
}

type Response_Headers_ExpiresDate struct {
	ExpiresDate *timestamp.Timestamp `protobuf:"bytes,10,opt,name=expires_date,json=expiresDate,proto3,oneof"`
}

func (*Response_Headers_ExpiresAlready) isResponse_Headers_Expires() {}

func (*Response_Headers_ExpiresDate) isResponse_Headers_Expires() {}

func (m *Response_Headers) GetExpires() isResponse_Headers_Expires {
	if m != nil {
		return m.Expires
	}
	return nil
}

func (m *Response_Headers) GetExpiresAlready() Already {
	if x, ok := m.GetExpires().(*Response_Headers_ExpiresAlready); ok {
		return x.ExpiresAlready
	}
	return Already_ALREADY
}

func (m *Response_Headers) GetExpiresDate() *timestamp.Timestamp {
	if x, ok := m.GetExpires().(*Response_Headers_ExpiresDate); ok {
		return x.ExpiresDate
	}
	return nil
}

func (m *Response_Headers) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

type isResponse_Headers_Vary interface {
	isResponse_Headers_Vary()
}

type Response_Headers_VaryAll struct {
	VaryAll Wildcard `protobuf:"varint,12,opt,name=vary_all,json=varyAll,proto3,enum=web.Wildcard,oneof"`
}

type Response_Headers_VaryHeaders struct {
	VaryHeaders *StringList `protobuf:"bytes,13,opt,name=vary_headers,json=varyHeaders,proto3,oneof"`
}

func (*Response_Headers_VaryAll) isResponse_Headers_Vary() {}

func (*Response_Headers_VaryHeaders) isResponse_Headers_Vary() {}

func (m *Response_Headers) GetVary() isResponse_Headers_Vary {
	if m != nil {
		return m.Vary
	}
	return nil
}

func (m *Response_Headers) GetVaryAll() Wildcard {
	if x, ok := m.GetVary().(*Response_Headers_VaryAll); ok {
		return x.VaryAll
	}
	return Wildcard_STAR
}

func (m *Response_Headers) GetVaryHeaders() *StringList {
	if x, ok := m.GetVary().(*Response_Headers_VaryHeaders); ok {
		return x.VaryHeaders
	}
	return nil
}

func (m *Response_Headers) GetXFrameOptions() Response_Headers_XFrameOptionsValue {
	if m != nil {
		return m.XFrameOptions
	}
	return Response_Headers_UNUSED_X_FRAME_OPTIONS_VALUE
}

func (m *Response_Headers) GetXXssProtection() string {
	if m != nil {
		return m.XXssProtection
	}
	return ""
}

func (m *Response_Headers) GetSetCookie() []*Response_Headers_SetCookieMessage {
	if m != nil {
		return m.SetCookie
	}
	return nil
}

func (m *Response_Headers) GetOther() []*KeyValue {
	if m != nil {
		return m.Other
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response_Headers) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_Headers_AccessControlAllowOriginAll)(nil),
		(*Response_Headers_AccessControlAllowOriginOrigins)(nil),
		(*Response_Headers_AltSvcClear)(nil),
		(*Response_Headers_Service)(nil),
		(*Response_Headers_ExpiresAlready)(nil),
		(*Response_Headers_ExpiresDate)(nil),
		(*Response_Headers_VaryAll)(nil),
		(*Response_Headers_VaryHeaders)(nil),
	}
}

type Response_Headers_AltSvcMessage struct {
	Services             []*Response_Headers_AltSvcMessage_Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	MaxAge               uint64                                    `protobuf:"varint,2,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	Persist              bool                                      `protobuf:"varint,3,opt,name=persist,proto3" json:"persist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *Response_Headers_AltSvcMessage) Reset()         { *m = Response_Headers_AltSvcMessage{} }
func (m *Response_Headers_AltSvcMessage) String() string { return proto.CompactTextString(m) }
func (*Response_Headers_AltSvcMessage) ProtoMessage()    {}
func (*Response_Headers_AltSvcMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{3, 0, 0}
}

func (m *Response_Headers_AltSvcMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Headers_AltSvcMessage.Unmarshal(m, b)
}
func (m *Response_Headers_AltSvcMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Headers_AltSvcMessage.Marshal(b, m, deterministic)
}
func (m *Response_Headers_AltSvcMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Headers_AltSvcMessage.Merge(m, src)
}
func (m *Response_Headers_AltSvcMessage) XXX_Size() int {
	return xxx_messageInfo_Response_Headers_AltSvcMessage.Size(m)
}
func (m *Response_Headers_AltSvcMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Headers_AltSvcMessage.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Headers_AltSvcMessage proto.InternalMessageInfo

func (m *Response_Headers_AltSvcMessage) GetServices() []*Response_Headers_AltSvcMessage_Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Response_Headers_AltSvcMessage) GetMaxAge() uint64 {
	if m != nil {
		return m.MaxAge
	}
	return 0
}

func (m *Response_Headers_AltSvcMessage) GetPersist() bool {
	if m != nil {
		return m.Persist
	}
	return false
}

type Response_Headers_AltSvcMessage_Service struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HostName             string   `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Headers_AltSvcMessage_Service) Reset() {
	*m = Response_Headers_AltSvcMessage_Service{}
}
func (m *Response_Headers_AltSvcMessage_Service) String() string { return proto.CompactTextString(m) }
func (*Response_Headers_AltSvcMessage_Service) ProtoMessage()    {}
func (*Response_Headers_AltSvcMessage_Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{3, 0, 0, 0}
}

func (m *Response_Headers_AltSvcMessage_Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Headers_AltSvcMessage_Service.Unmarshal(m, b)
}
func (m *Response_Headers_AltSvcMessage_Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Headers_AltSvcMessage_Service.Marshal(b, m, deterministic)
}
func (m *Response_Headers_AltSvcMessage_Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Headers_AltSvcMessage_Service.Merge(m, src)
}
func (m *Response_Headers_AltSvcMessage_Service) XXX_Size() int {
	return xxx_messageInfo_Response_Headers_AltSvcMessage_Service.Size(m)
}
func (m *Response_Headers_AltSvcMessage_Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Headers_AltSvcMessage_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Headers_AltSvcMessage_Service proto.InternalMessageInfo

func (m *Response_Headers_AltSvcMessage_Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response_Headers_AltSvcMessage_Service) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *Response_Headers_AltSvcMessage_Service) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Response_Headers_SetCookieMessage struct {
	Name                 string                                          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string                                          `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Expires              *timestamp.Timestamp                            `protobuf:"bytes,3,opt,name=expires,proto3" json:"expires,omitempty"`
	MaxAge               int64                                           `protobuf:"varint,4,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	Domain               string                                          `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	Path                 string                                          `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Secure               bool                                            `protobuf:"varint,7,opt,name=secure,proto3" json:"secure,omitempty"`
	HttpOnly             bool                                            `protobuf:"varint,8,opt,name=http_only,json=httpOnly,proto3" json:"http_only,omitempty"`
	Samesite             Response_Headers_SetCookieMessage_SameSiteValue `protobuf:"varint,9,opt,name=samesite,proto3,enum=web.Response_Headers_SetCookieMessage_SameSiteValue" json:"samesite,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *Response_Headers_SetCookieMessage) Reset()         { *m = Response_Headers_SetCookieMessage{} }
func (m *Response_Headers_SetCookieMessage) String() string { return proto.CompactTextString(m) }
func (*Response_Headers_SetCookieMessage) ProtoMessage()    {}
func (*Response_Headers_SetCookieMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{3, 0, 1}
}

func (m *Response_Headers_SetCookieMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Headers_SetCookieMessage.Unmarshal(m, b)
}
func (m *Response_Headers_SetCookieMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Headers_SetCookieMessage.Marshal(b, m, deterministic)
}
func (m *Response_Headers_SetCookieMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Headers_SetCookieMessage.Merge(m, src)
}
func (m *Response_Headers_SetCookieMessage) XXX_Size() int {
	return xxx_messageInfo_Response_Headers_SetCookieMessage.Size(m)
}
func (m *Response_Headers_SetCookieMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Headers_SetCookieMessage.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Headers_SetCookieMessage proto.InternalMessageInfo

func (m *Response_Headers_SetCookieMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response_Headers_SetCookieMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Response_Headers_SetCookieMessage) GetExpires() *timestamp.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

func (m *Response_Headers_SetCookieMessage) GetMaxAge() int64 {
	if m != nil {
		return m.MaxAge
	}
	return 0
}

func (m *Response_Headers_SetCookieMessage) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Response_Headers_SetCookieMessage) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Response_Headers_SetCookieMessage) GetSecure() bool {
	if m != nil {
		return m.Secure
	}
	return false
}

func (m *Response_Headers_SetCookieMessage) GetHttpOnly() bool {
	if m != nil {
		return m.HttpOnly
	}
	return false
}

func (m *Response_Headers_SetCookieMessage) GetSamesite() Response_Headers_SetCookieMessage_SameSiteValue {
	if m != nil {
		return m.Samesite
	}
	return Response_Headers_SetCookieMessage_UNUSED_SAMESITE_VALUE
}

func init() {
	proto.RegisterEnum("web.Encodings", Encodings_name, Encodings_value)
	proto.RegisterEnum("web.CacheControlResponse_Directives", CacheControlResponse_Directives_name, CacheControlResponse_Directives_value)
	proto.RegisterEnum("web.Response_Headers_AccessControlAllowCredentialsValue", Response_Headers_AccessControlAllowCredentialsValue_name, Response_Headers_AccessControlAllowCredentialsValue_value)
	proto.RegisterEnum("web.Response_Headers_XFrameOptionsValue", Response_Headers_XFrameOptionsValue_name, Response_Headers_XFrameOptionsValue_value)
	proto.RegisterEnum("web.Response_Headers_SetCookieMessage_SameSiteValue", Response_Headers_SetCookieMessage_SameSiteValue_name, Response_Headers_SetCookieMessage_SameSiteValue_value)
	proto.RegisterType((*StringList)(nil), "web.StringList")
	proto.RegisterType((*CacheControlResponse)(nil), "web.CacheControlResponse")
	proto.RegisterType((*Request)(nil), "web.Request")
	proto.RegisterType((*Response)(nil), "web.Response")
	proto.RegisterType((*Response_Headers)(nil), "web.Response.Headers")
	proto.RegisterType((*Response_Headers_AltSvcMessage)(nil), "web.Response.Headers.AltSvcMessage")
	proto.RegisterType((*Response_Headers_AltSvcMessage_Service)(nil), "web.Response.Headers.AltSvcMessage.Service")
	proto.RegisterType((*Response_Headers_SetCookieMessage)(nil), "web.Response.Headers.SetCookieMessage")
}

func init() { proto.RegisterFile("web.proto", fileDescriptor_461bb3ac99194e85) }

var fileDescriptor_461bb3ac99194e85 = []byte{
	// 1444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x4f, 0x6f, 0xdb, 0xca,
	0x11, 0x37, 0x25, 0x59, 0x12, 0x47, 0x7f, 0xcc, 0xee, 0xcb, 0x7b, 0x65, 0x94, 0x06, 0x16, 0xe4,
	0x22, 0x10, 0x12, 0x44, 0x49, 0xd5, 0x00, 0xed, 0xa9, 0x01, 0x4d, 0xd1, 0x16, 0x51, 0x89, 0x14,
	0x96, 0x92, 0xe3, 0xf4, 0xb2, 0xa0, 0xa9, 0x8d, 0x4d, 0x94, 0x12, 0x15, 0x2e, 0x65, 0x4b, 0xc7,
	0x1e, 0xfb, 0x45, 0x7a, 0xed, 0xc7, 0xe9, 0xa1, 0xed, 0x77, 0x79, 0xd8, 0xe5, 0xd2, 0x7f, 0x12,
	0x39, 0xc9, 0x45, 0xda, 0x99, 0xfd, 0xcd, 0xcc, 0xce, 0xf0, 0x37, 0xb3, 0x0b, 0xea, 0x0d, 0xbd,
	0xe8, 0xad, 0x92, 0x38, 0x8d, 0x51, 0xf1, 0x86, 0x5e, 0xb4, 0x0e, 0x2f, 0xe3, 0xf8, 0x32, 0xa2,
	0x6f, 0x84, 0xea, 0x62, 0xfd, 0xe9, 0x4d, 0x1a, 0x2e, 0x28, 0x4b, 0xfd, 0xc5, 0x2a, 0x43, 0xb5,
	0x60, 0x11, 0x2e, 0xa8, 0x5c, 0xd7, 0x59, 0xea, 0xa7, 0x6b, 0x26, 0xa5, 0xc6, 0x15, 0xf5, 0xe7,
	0x34, 0x91, 0x62, 0xe7, 0x05, 0x80, 0x97, 0x26, 0xe1, 0xf2, 0x72, 0x14, 0xb2, 0x14, 0xe9, 0x50,
	0x61, 0x42, 0x62, 0xba, 0xd2, 0x2e, 0x76, 0x55, 0x9c, 0x8b, 0x9d, 0x7f, 0x15, 0xe0, 0x89, 0xe9,
	0x07, 0x57, 0xd4, 0x8c, 0x97, 0x69, 0x12, 0x47, 0x98, 0xb2, 0x55, 0xbc, 0x64, 0x14, 0x1d, 0x83,
	0x3a, 0x0f, 0x13, 0x1a, 0xa4, 0xe1, 0x35, 0xd5, 0x95, 0xb6, 0xd2, 0x6d, 0xf6, 0x7f, 0xdf, 0xe3,
	0xc7, 0xdd, 0x85, 0xee, 0x0d, 0x72, 0x28, 0xc3, 0x77, 0x66, 0x22, 0x2c, 0x0d, 0xe2, 0xe5, 0x9c,
	0xe9, 0x85, 0xb6, 0xd2, 0x2d, 0xe1, 0x5c, 0xec, 0xfc, 0x5b, 0x01, 0xb8, 0xb3, 0x41, 0x4f, 0x40,
	0x9b, 0x39, 0x33, 0xcf, 0x1a, 0x90, 0x81, 0x8d, 0x2d, 0x73, 0x6a, 0x9f, 0x59, 0xda, 0x1e, 0xfa,
	0x09, 0x0e, 0xc6, 0x33, 0x6f, 0x4a, 0xb0, 0x75, 0x66, 0x8c, 0xec, 0x81, 0x31, 0xb5, 0x34, 0x05,
	0xd5, 0xa1, 0xea, 0xb8, 0xc4, 0x34, 0xcc, 0xa1, 0xa5, 0x15, 0xa4, 0xe4, 0x4d, 0x5d, 0x6c, 0x69,
	0x45, 0xa4, 0x41, 0xdd, 0x71, 0xc9, 0x14, 0x1b, 0x8e, 0x77, 0xe2, 0xe2, 0xb1, 0x56, 0x42, 0x00,
	0xe5, 0xc9, 0xec, 0x78, 0x64, 0x9b, 0xda, 0x3e, 0xaa, 0x41, 0x65, 0x82, 0xed, 0x33, 0xee, 0xa6,
	0xcc, 0x23, 0x4e, 0xb0, 0x7b, 0xfe, 0xf1, 0xbe, 0xf3, 0x0a, 0x87, 0x8c, 0x8d, 0x73, 0x62, 0x9c,
	0x5a, 0x5a, 0x95, 0xfb, 0xf6, 0xc8, 0xd8, 0x38, 0xe7, 0x92, 0xda, 0xf9, 0x9f, 0x02, 0x15, 0x4c,
	0x3f, 0xaf, 0x29, 0x4b, 0xd1, 0x11, 0x94, 0x17, 0x34, 0xbd, 0x8a, 0xe7, 0xb2, 0x30, 0x35, 0x51,
	0x98, 0xb1, 0x50, 0x61, 0xb9, 0x85, 0xfa, 0x50, 0x5f, 0x27, 0x21, 0xb9, 0x09, 0xa3, 0x79, 0xe0,
	0x27, 0x73, 0x51, 0x81, 0x66, 0xbf, 0x21, 0xa0, 0x1f, 0xa4, 0x72, 0xb8, 0x87, 0x6b, 0xeb, 0x24,
	0xcc, 0x45, 0x74, 0x08, 0xc0, 0x6d, 0xb2, 0x8f, 0xa3, 0x17, 0xdb, 0x4a, 0x57, 0x1d, 0xee, 0x61,
	0x75, 0x9d, 0x84, 0xd9, 0xc7, 0x44, 0x47, 0xb0, 0xff, 0x79, 0x4d, 0x93, 0xad, 0x5e, 0x6a, 0x17,
	0xbb, 0x35, 0xe9, 0xed, 0xaf, 0x74, 0x7b, 0xe6, 0x47, 0x6b, 0x8a, 0xb3, 0x3d, 0xf4, 0x0a, 0xca,
	0x19, 0x19, 0xf4, 0xfd, 0xb6, 0xd2, 0xad, 0xf5, 0x7f, 0x12, 0x28, 0x79, 0xf8, 0x61, 0x46, 0x13,
	0x2c, 0x21, 0xc7, 0xfb, 0x50, 0x9c, 0x61, 0xbb, 0xf3, 0x1f, 0x0d, 0xaa, 0xb7, 0xdf, 0xbe, 0x0b,
	0xe5, 0x8c, 0x5b, 0x32, 0x3f, 0x4d, 0x38, 0xf0, 0x84, 0xca, 0x8c, 0xe7, 0x94, 0x61, 0xb9, 0x8f,
	0x5e, 0xdf, 0x86, 0x2a, 0x88, 0x50, 0x3f, 0xcb, 0x50, 0x92, 0x16, 0x5f, 0x04, 0x43, 0x08, 0x4a,
	0x17, 0xf1, 0x7c, 0x2b, 0x32, 0xab, 0x63, 0xb1, 0x6e, 0xfd, 0xff, 0x00, 0x2a, 0x12, 0x87, 0x66,
	0x70, 0xe8, 0x07, 0x01, 0x65, 0x8c, 0x04, 0x19, 0xc1, 0x88, 0x1f, 0x45, 0xf1, 0x0d, 0x89, 0x93,
	0xf0, 0x32, 0x5c, 0x72, 0x41, 0x9e, 0xe8, 0xab, 0x32, 0x3e, 0xcb, 0xec, 0x24, 0x2f, 0x0d, 0x6e,
	0xe5, 0x0a, 0x23, 0x23, 0x8a, 0x10, 0x81, 0xa3, 0x6f, 0xb9, 0xcd, 0xfe, 0x98, 0x4c, 0xe1, 0x40,
	0x26, 0x9b, 0x37, 0xcf, 0x70, 0x0f, 0x1f, 0x3e, 0xe6, 0x3c, 0xfb, 0x65, 0xe8, 0x1f, 0x0a, 0xb4,
	0x77, 0x46, 0x08, 0x12, 0x3a, 0xa7, 0xcb, 0x34, 0xf4, 0x23, 0x26, 0x92, 0x6e, 0xf6, 0xff, 0xbc,
	0xb3, 0x42, 0x3d, 0xe3, 0xab, 0x08, 0xe6, 0x9d, 0x69, 0xf6, 0x75, 0x9f, 0xfb, 0xdf, 0xc2, 0x20,
	0x03, 0x9e, 0x7f, 0x71, 0x04, 0xba, 0x59, 0xc5, 0x8c, 0x12, 0x39, 0x18, 0x04, 0x65, 0x54, 0xdc,
	0x7a, 0xe0, 0xc5, 0x12, 0x90, 0xbc, 0xfc, 0x6f, 0xa1, 0xe1, 0x47, 0x29, 0x61, 0xd7, 0x01, 0x09,
	0x22, 0xea, 0x67, 0xfc, 0x69, 0xf6, 0x21, 0xeb, 0x7b, 0xae, 0x19, 0x2a, 0xb8, 0xe6, 0x47, 0xa9,
	0x77, 0x1d, 0x08, 0x11, 0xbd, 0xe7, 0x1d, 0x9e, 0x5c, 0x87, 0x01, 0xd5, 0xcb, 0xa2, 0x7a, 0x47,
	0x8f, 0xa4, 0x27, 0x6c, 0xc6, 0x94, 0x31, 0xff, 0x92, 0x0e, 0x15, 0x9c, 0x5b, 0xa1, 0xbf, 0x40,
	0x23, 0xe0, 0x03, 0x25, 0x3f, 0xb4, 0x8e, 0x84, 0x9b, 0xa7, 0x8f, 0x8e, 0x1a, 0x5c, 0x0f, 0xee,
	0x69, 0xd1, 0x5b, 0xa8, 0x73, 0x4b, 0xba, 0x4c, 0x49, 0xba, 0x5d, 0x51, 0xbd, 0x22, 0xcc, 0x33,
	0x7a, 0x8c, 0xed, 0xb1, 0x35, 0xdd, 0xae, 0x28, 0xae, 0x49, 0x08, 0x17, 0x50, 0x0f, 0x4a, 0x73,
	0x3f, 0xa5, 0x7a, 0x55, 0x20, 0x5b, 0xbd, 0x6c, 0xe4, 0xf6, 0xf2, 0x91, 0xdb, 0x9b, 0xe6, 0x23,
	0x17, 0x0b, 0x1c, 0xfa, 0x13, 0x1c, 0xd0, 0xcd, 0x2a, 0x4c, 0x28, 0x23, 0x7e, 0x94, 0x50, 0x7f,
	0xbe, 0xd5, 0x55, 0x51, 0x96, 0xba, 0x08, 0x62, 0x64, 0xba, 0x61, 0x01, 0x37, 0x25, 0x4c, 0x6a,
	0xd0, 0x7b, 0xa8, 0xe7, 0x86, 0x22, 0x20, 0x7c, 0x2f, 0xe0, 0xb0, 0x80, 0x6b, 0xd2, 0x62, 0xc0,
	0x23, 0xff, 0x02, 0x65, 0x5e, 0x26, 0x9a, 0xe8, 0x35, 0x3e, 0x09, 0xb0, 0x94, 0xd0, 0x4b, 0xa8,
	0x5e, 0xfb, 0xc9, 0x56, 0xb4, 0x43, 0x7d, 0x57, 0x3b, 0x14, 0x71, 0x85, 0x03, 0x38, 0xf5, 0xdf,
	0x41, 0x5d, 0x60, 0x73, 0x12, 0x34, 0x76, 0x73, 0xbc, 0x88, 0x6b, 0x1c, 0x96, 0x13, 0x61, 0x02,
	0x07, 0x1b, 0xf2, 0x29, 0xf1, 0x17, 0x94, 0xc4, 0xab, 0x34, 0x8c, 0x97, 0x4c, 0xd7, 0x44, 0xa0,
	0xee, 0xee, 0xcf, 0x7b, 0x7e, 0xc2, 0xb1, 0x6e, 0x06, 0xcd, 0xd8, 0xda, 0xd8, 0xdc, 0xd7, 0xa1,
	0x2e, 0x68, 0x1b, 0xb2, 0x61, 0x8c, 0xf0, 0xb4, 0xf9, 0xd8, 0x8f, 0x97, 0xfa, 0x81, 0xc8, 0xaa,
	0xb9, 0x39, 0x67, 0x6c, 0x72, 0xab, 0x45, 0x16, 0x00, 0xa3, 0x29, 0x09, 0xe2, 0xf8, 0xef, 0x21,
	0xd5, 0x9b, 0x62, 0xce, 0xbd, 0xd8, 0x1d, 0xd6, 0xa3, 0xa9, 0x29, 0x60, 0x92, 0x58, 0x58, 0x65,
	0xb9, 0x86, 0x4f, 0xca, 0x38, 0xbd, 0xa2, 0x89, 0xfe, 0x9b, 0x9d, 0x93, 0x52, 0xec, 0xb5, 0xfe,
	0xab, 0x40, 0xe3, 0x01, 0x35, 0xd1, 0x29, 0x54, 0x25, 0x35, 0xb3, 0xab, 0xb2, 0xd6, 0x7f, 0xf5,
	0x03, 0x8c, 0xee, 0x79, 0x99, 0x0d, 0xbe, 0x35, 0x46, 0xbf, 0x85, 0xca, 0xc2, 0xdf, 0x10, 0xff,
	0x92, 0xca, 0xbb, 0xaf, 0xbc, 0xf0, 0x37, 0xc6, 0xa5, 0xb8, 0x14, 0x57, 0x34, 0x61, 0x21, 0x4b,
	0xc5, 0x44, 0xa8, 0xe2, 0x5c, 0x6c, 0x39, 0x50, 0x91, 0x7e, 0xf8, 0xa0, 0x5c, 0xfa, 0x8b, 0xec,
	0xe2, 0x55, 0xb1, 0x58, 0xa3, 0x67, 0xa0, 0x5e, 0xc5, 0x2c, 0x25, 0x62, 0xa3, 0x20, 0x36, 0xaa,
	0x5c, 0xe1, 0xf0, 0x4d, 0x04, 0xa5, 0x55, 0x9c, 0x64, 0x2e, 0x1b, 0x58, 0xac, 0x5b, 0xff, 0x2c,
	0x82, 0xf6, 0x65, 0x89, 0x76, 0x7a, 0x7e, 0x02, 0xfb, 0xd7, 0xbc, 0x2c, 0xd2, 0x6b, 0x26, 0xa0,
	0x77, 0x50, 0x91, 0x6c, 0x14, 0x5e, 0xbf, 0xdd, 0x2b, 0x39, 0xf4, 0x7e, 0xde, 0xa5, 0xb6, 0xd2,
	0x2d, 0xde, 0xe6, 0xfd, 0x0b, 0x94, 0xe7, 0xf1, 0xc2, 0x0f, 0x97, 0x62, 0xaa, 0xa8, 0x58, 0x4a,
	0xe2, 0xe4, 0x7e, 0x7a, 0x25, 0xe6, 0x87, 0x8a, 0xc5, 0x3a, 0x63, 0x7e, 0xb0, 0x4e, 0xb2, 0x7e,
	0xae, 0x62, 0x29, 0x89, 0x12, 0xa4, 0xe9, 0x8a, 0xc4, 0xcb, 0x68, 0x2b, 0x1a, 0xb8, 0x8a, 0xab,
	0x5c, 0xe1, 0x2e, 0xa3, 0x2d, 0x9a, 0x40, 0x95, 0xf9, 0x0b, 0xca, 0xc2, 0x94, 0xca, 0x0e, 0x7d,
	0xf7, 0x63, 0xb4, 0xe9, 0x79, 0xfe, 0x82, 0x7a, 0x61, 0x4a, 0x33, 0x6e, 0xdc, 0x7a, 0xe9, 0xd8,
	0xd0, 0x78, 0xb0, 0x85, 0x9e, 0xc2, 0xcf, 0xf2, 0x9d, 0xe2, 0x19, 0x63, 0xcb, 0xb3, 0xa7, 0x16,
	0x39, 0x33, 0x46, 0x33, 0xfe, 0x58, 0x01, 0x28, 0x7b, 0x53, 0x6c, 0x9b, 0x53, 0x4d, 0x41, 0x15,
	0x28, 0x8e, 0x8c, 0x73, 0xad, 0x80, 0xaa, 0x50, 0x72, 0x5c, 0xc7, 0xd2, 0x8a, 0x9d, 0x08, 0x3a,
	0xdf, 0x1f, 0xf1, 0xe8, 0x0f, 0xf0, 0x5a, 0xfa, 0x37, 0x4c, 0xd3, 0xf2, 0x3c, 0x62, 0xba, 0xce,
	0x14, 0xbb, 0x23, 0x62, 0x8c, 0x46, 0xee, 0x07, 0x62, 0x62, 0x6b, 0x60, 0x39, 0x53, 0xdb, 0x18,
	0x79, 0xb7, 0x71, 0x55, 0xd8, 0x3f, 0x31, 0x46, 0x1e, 0x7f, 0x1a, 0x55, 0xa1, 0x34, 0xc5, 0x33,
	0x4b, 0x2b, 0x74, 0x26, 0x80, 0xbe, 0x6e, 0x49, 0xd4, 0x86, 0xdf, 0x49, 0xef, 0xe7, 0xe4, 0x04,
	0x1b, 0x63, 0x8b, 0xb8, 0x93, 0xa9, 0xed, 0x3a, 0x77, 0xce, 0xaa, 0x50, 0x1a, 0x58, 0xce, 0x47,
	0x4d, 0x41, 0x4d, 0x00, 0x9e, 0xa2, 0x8b, 0xed, 0x53, 0xdb, 0xd1, 0x0a, 0xc7, 0x2d, 0xd0, 0x8d,
	0x47, 0x2e, 0xc1, 0x63, 0x15, 0x2a, 0x46, 0x94, 0x12, 0xef, 0x3a, 0xe0, 0x4b, 0x2b, 0x23, 0xc2,
	0x71, 0x19, 0x4a, 0x67, 0x7e, 0xb2, 0x7d, 0xe9, 0x83, 0x6a, 0x2d, 0x83, 0x78, 0xce, 0x9f, 0x9b,
	0xbc, 0x80, 0x96, 0x63, 0xba, 0x03, 0xdb, 0x39, 0xf5, 0xc8, 0xcc, 0xf1, 0x26, 0x96, 0x69, 0x9f,
	0xd8, 0xd6, 0x40, 0xdb, 0xe3, 0xcf, 0x2d, 0x5b, 0x64, 0x37, 0xfd, 0x98, 0xe5, 0x72, 0xfa, 0x37,
	0x7b, 0x92, 0x3d, 0xf1, 0x4c, 0x77, 0x3c, 0xc1, 0x96, 0xe7, 0x69, 0x45, 0xfe, 0x42, 0x1b, 0x58,
	0x27, 0x23, 0xfe, 0x5c, 0x2b, 0xa1, 0x32, 0x14, 0x8e, 0xb1, 0xb6, 0xdf, 0x7f, 0x09, 0xc5, 0x0f,
	0xf4, 0x02, 0x1d, 0x41, 0x61, 0xe0, 0xa2, 0xfa, 0xfd, 0xd7, 0x4e, 0xab, 0xf1, 0x80, 0x02, 0x6f,
	0x95, 0x8b, 0xb2, 0x20, 0xef, 0x1f, 0x7f, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x17, 0x1d, 0x06,
	0x7b, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WebClient is the client API for Web service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebClient interface {
	// TODO: should the methods be captured here? separate request/response messages?
	DO(ctx context.Context, in *Request, opts ...grpc.CallOption) (Web_DOClient, error)
}

type webClient struct {
	cc *grpc.ClientConn
}

func NewWebClient(cc *grpc.ClientConn) WebClient {
	return &webClient{cc}
}

func (c *webClient) DO(ctx context.Context, in *Request, opts ...grpc.CallOption) (Web_DOClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Web_serviceDesc.Streams[0], "/web.Web/DO", opts...)
	if err != nil {
		return nil, err
	}
	x := &webDOClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Web_DOClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type webDOClient struct {
	grpc.ClientStream
}

func (x *webDOClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WebServer is the server API for Web service.
type WebServer interface {
	// TODO: should the methods be captured here? separate request/response messages?
	DO(*Request, Web_DOServer) error
}

// UnimplementedWebServer can be embedded to have forward compatible implementations.
type UnimplementedWebServer struct {
}

func (*UnimplementedWebServer) DO(req *Request, srv Web_DOServer) error {
	return status.Errorf(codes.Unimplemented, "method DO not implemented")
}

func RegisterWebServer(s *grpc.Server, srv WebServer) {
	s.RegisterService(&_Web_serviceDesc, srv)
}

func _Web_DO_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WebServer).DO(m, &webDOServer{stream})
}

type Web_DOServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type webDOServer struct {
	grpc.ServerStream
}

func (x *webDOServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

var _Web_serviceDesc = grpc.ServiceDesc{
	ServiceName: "web.Web",
	HandlerType: (*WebServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DO",
			Handler:       _Web_DO_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "web.proto",
}
