// Code generated by protoc-gen-go. DO NOT EDIT.
// source: web.proto

package web

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Wildcard int32

const (
	Wildcard_STAR Wildcard = 0
)

var Wildcard_name = map[int32]string{
	0: "STAR",
}

var Wildcard_value = map[string]int32{
	"STAR": 0,
}

func (x Wildcard) String() string {
	return proto.EnumName(Wildcard_name, int32(x))
}

func (Wildcard) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{0}
}

type Already int32

const (
	Already_ALREADY Already = 0
)

var Already_name = map[int32]string{
	0: "ALREADY",
}

var Already_value = map[string]int32{
	"ALREADY": 0,
}

func (x Already) String() string {
	return proto.EnumName(Already_name, int32(x))
}

func (Already) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{1}
}

type Clear int32

const (
	Clear_CLEAR Clear = 0
)

var Clear_name = map[int32]string{
	0: "CLEAR",
}

var Clear_value = map[string]int32{
	"CLEAR": 0,
}

func (x Clear) String() string {
	return proto.EnumName(Clear_name, int32(x))
}

func (Clear) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{2}
}

type Cache_Control_Request_Directives int32

const (
	Cache_Control_Request_UNUSED_DIRECTIVE Cache_Control_Request_Directives = 0
	Cache_Control_Request_MAX_AGE          Cache_Control_Request_Directives = 1
	Cache_Control_Request_MAX_STALE        Cache_Control_Request_Directives = 2
	Cache_Control_Request_MIN_FRESH        Cache_Control_Request_Directives = 3
	Cache_Control_Request_NO_CACHE         Cache_Control_Request_Directives = 4
	Cache_Control_Request_NO_STORE         Cache_Control_Request_Directives = 5
	Cache_Control_Request_NO_TRANSFORM     Cache_Control_Request_Directives = 6
	Cache_Control_Request_ONLY_OF_CACHED   Cache_Control_Request_Directives = 7
)

var Cache_Control_Request_Directives_name = map[int32]string{
	0: "UNUSED_DIRECTIVE",
	1: "MAX_AGE",
	2: "MAX_STALE",
	3: "MIN_FRESH",
	4: "NO_CACHE",
	5: "NO_STORE",
	6: "NO_TRANSFORM",
	7: "ONLY_OF_CACHED",
}

var Cache_Control_Request_Directives_value = map[string]int32{
	"UNUSED_DIRECTIVE": 0,
	"MAX_AGE":          1,
	"MAX_STALE":        2,
	"MIN_FRESH":        3,
	"NO_CACHE":         4,
	"NO_STORE":         5,
	"NO_TRANSFORM":     6,
	"ONLY_OF_CACHED":   7,
}

func (x Cache_Control_Request_Directives) String() string {
	return proto.EnumName(Cache_Control_Request_Directives_name, int32(x))
}

func (Cache_Control_Request_Directives) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{2, 0}
}

type Cache_Control_Response_Directives int32

const (
	Cache_Control_Response_UNUSED_DIRECTIVE Cache_Control_Response_Directives = 0
	Cache_Control_Response_MUST_REVALIDATE  Cache_Control_Response_Directives = 1
	Cache_Control_Response_NO_CACHE         Cache_Control_Response_Directives = 2
	Cache_Control_Response_NO_STORE         Cache_Control_Response_Directives = 3
	Cache_Control_Response_NO_TRANSFORM     Cache_Control_Response_Directives = 4
	Cache_Control_Response_PUBLIC           Cache_Control_Response_Directives = 5
	Cache_Control_Response_PRIVATE          Cache_Control_Response_Directives = 6
	Cache_Control_Response_PROXY_REVALIDATE Cache_Control_Response_Directives = 7
	Cache_Control_Response_MAX_AGE          Cache_Control_Response_Directives = 8
	Cache_Control_Response_S_MAXAGE         Cache_Control_Response_Directives = 9
)

var Cache_Control_Response_Directives_name = map[int32]string{
	0: "UNUSED_DIRECTIVE",
	1: "MUST_REVALIDATE",
	2: "NO_CACHE",
	3: "NO_STORE",
	4: "NO_TRANSFORM",
	5: "PUBLIC",
	6: "PRIVATE",
	7: "PROXY_REVALIDATE",
	8: "MAX_AGE",
	9: "S_MAXAGE",
}

var Cache_Control_Response_Directives_value = map[string]int32{
	"UNUSED_DIRECTIVE": 0,
	"MUST_REVALIDATE":  1,
	"NO_CACHE":         2,
	"NO_STORE":         3,
	"NO_TRANSFORM":     4,
	"PUBLIC":           5,
	"PRIVATE":          6,
	"PROXY_REVALIDATE": 7,
	"MAX_AGE":          8,
	"S_MAXAGE":         9,
}

func (x Cache_Control_Response_Directives) String() string {
	return proto.EnumName(Cache_Control_Response_Directives_name, int32(x))
}

func (Cache_Control_Response_Directives) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{3, 0}
}

type Request_Method int32

const (
	Request_UNUSED_METHOD Request_Method = 0
	Request_GET           Request_Method = 1
	Request_HEAD          Request_Method = 2
	Request_POST          Request_Method = 3
	Request_PUT           Request_Method = 4
	Request_DELETE        Request_Method = 5
	Request_CONNECT       Request_Method = 6
	Request_OPTIONS       Request_Method = 7
	Request_TRACE         Request_Method = 8
)

var Request_Method_name = map[int32]string{
	0: "UNUSED_METHOD",
	1: "GET",
	2: "HEAD",
	3: "POST",
	4: "PUT",
	5: "DELETE",
	6: "CONNECT",
	7: "OPTIONS",
	8: "TRACE",
}

var Request_Method_value = map[string]int32{
	"UNUSED_METHOD": 0,
	"GET":           1,
	"HEAD":          2,
	"POST":          3,
	"PUT":           4,
	"DELETE":        5,
	"CONNECT":       6,
	"OPTIONS":       7,
	"TRACE":         8,
}

func (x Request_Method) String() string {
	return proto.EnumName(Request_Method_name, int32(x))
}

func (Request_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{4, 0}
}

type Request_Headers_Transfer_Encodings_Value int32

const (
	Request_Headers_UNUSED_TRANSFER_ENCODINGS_VALUE Request_Headers_Transfer_Encodings_Value = 0
	Request_Headers_TRAILERS                        Request_Headers_Transfer_Encodings_Value = 1
)

var Request_Headers_Transfer_Encodings_Value_name = map[int32]string{
	0: "UNUSED_TRANSFER_ENCODINGS_VALUE",
	1: "TRAILERS",
}

var Request_Headers_Transfer_Encodings_Value_value = map[string]int32{
	"UNUSED_TRANSFER_ENCODINGS_VALUE": 0,
	"TRAILERS":                        1,
}

func (x Request_Headers_Transfer_Encodings_Value) String() string {
	return proto.EnumName(Request_Headers_Transfer_Encodings_Value_name, int32(x))
}

func (Request_Headers_Transfer_Encodings_Value) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{4, 0, 0}
}

type Request_Headers_X_Requested_With_Value int32

const (
	Request_Headers_UNUSED_X_REQUESTED_WITH_VALUE Request_Headers_X_Requested_With_Value = 0
	Request_Headers_XMLHTTPREQUEST                Request_Headers_X_Requested_With_Value = 1
)

var Request_Headers_X_Requested_With_Value_name = map[int32]string{
	0: "UNUSED_X_REQUESTED_WITH_VALUE",
	1: "XMLHTTPREQUEST",
}

var Request_Headers_X_Requested_With_Value_value = map[string]int32{
	"UNUSED_X_REQUESTED_WITH_VALUE": 0,
	"XMLHTTPREQUEST":                1,
}

func (x Request_Headers_X_Requested_With_Value) String() string {
	return proto.EnumName(Request_Headers_X_Requested_With_Value_name, int32(x))
}

func (Request_Headers_X_Requested_With_Value) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{4, 0, 1}
}

type Request_Headers_DNT_Value int32

const (
	Request_Headers_UNUSED_DNT_VALUE Request_Headers_DNT_Value = 0
	Request_Headers_DISABLED         Request_Headers_DNT_Value = 1
	Request_Headers_ENABLED          Request_Headers_DNT_Value = 2
)

var Request_Headers_DNT_Value_name = map[int32]string{
	0: "UNUSED_DNT_VALUE",
	1: "DISABLED",
	2: "ENABLED",
}

var Request_Headers_DNT_Value_value = map[string]int32{
	"UNUSED_DNT_VALUE": 0,
	"DISABLED":         1,
	"ENABLED":          2,
}

func (x Request_Headers_DNT_Value) String() string {
	return proto.EnumName(Request_Headers_DNT_Value_name, int32(x))
}

func (Request_Headers_DNT_Value) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{4, 0, 2}
}

type Response_Code_Value int32

const (
	Response_UNUSED_CODE Response_Code_Value = 0
	Response_OK          Response_Code_Value = 200
)

var Response_Code_Value_name = map[int32]string{
	0:   "UNUSED_CODE",
	200: "OK",
}

var Response_Code_Value_value = map[string]int32{
	"UNUSED_CODE": 0,
	"OK":          200,
}

func (x Response_Code_Value) String() string {
	return proto.EnumName(Response_Code_Value_name, int32(x))
}

func (Response_Code_Value) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{5, 0}
}

type Response_Headers_Access_Control_Allow_Credentials_Value int32

const (
	Response_Headers_UNUSED_ACCESS_CONTROL_ALLOW_CREDENTIALS_VALUE Response_Headers_Access_Control_Allow_Credentials_Value = 0
	Response_Headers_FALSE                                         Response_Headers_Access_Control_Allow_Credentials_Value = 1
	Response_Headers_TRUE                                          Response_Headers_Access_Control_Allow_Credentials_Value = 2
)

var Response_Headers_Access_Control_Allow_Credentials_Value_name = map[int32]string{
	0: "UNUSED_ACCESS_CONTROL_ALLOW_CREDENTIALS_VALUE",
	1: "FALSE",
	2: "TRUE",
}

var Response_Headers_Access_Control_Allow_Credentials_Value_value = map[string]int32{
	"UNUSED_ACCESS_CONTROL_ALLOW_CREDENTIALS_VALUE": 0,
	"FALSE": 1,
	"TRUE":  2,
}

func (x Response_Headers_Access_Control_Allow_Credentials_Value) String() string {
	return proto.EnumName(Response_Headers_Access_Control_Allow_Credentials_Value_name, int32(x))
}

func (Response_Headers_Access_Control_Allow_Credentials_Value) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{5, 0, 0}
}

type Response_Headers_X_Frame_Options_Value int32

const (
	Response_Headers_UNUSED_X_FRAME_OPTIONS_VALUE Response_Headers_X_Frame_Options_Value = 0
	Response_Headers_DENY                         Response_Headers_X_Frame_Options_Value = 1
	Response_Headers_SAMEORIGIN                   Response_Headers_X_Frame_Options_Value = 2
)

var Response_Headers_X_Frame_Options_Value_name = map[int32]string{
	0: "UNUSED_X_FRAME_OPTIONS_VALUE",
	1: "DENY",
	2: "SAMEORIGIN",
}

var Response_Headers_X_Frame_Options_Value_value = map[string]int32{
	"UNUSED_X_FRAME_OPTIONS_VALUE": 0,
	"DENY":                         1,
	"SAMEORIGIN":                   2,
}

func (x Response_Headers_X_Frame_Options_Value) String() string {
	return proto.EnumName(Response_Headers_X_Frame_Options_Value_name, int32(x))
}

func (Response_Headers_X_Frame_Options_Value) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{5, 0, 1}
}

// Explicitly encoding the most common MIME types saves space on the wire
type Response_Headers_Content_Type_Message_Common_MIME_Types int32

const (
	Response_Headers_Content_Type_Message_UNUSED_MIME_TYPE         Response_Headers_Content_Type_Message_Common_MIME_Types = 0
	Response_Headers_Content_Type_Message_APPLICATION_OCTET_STREAM Response_Headers_Content_Type_Message_Common_MIME_Types = 1
	Response_Headers_Content_Type_Message_TEXT_HTML                Response_Headers_Content_Type_Message_Common_MIME_Types = 2
)

var Response_Headers_Content_Type_Message_Common_MIME_Types_name = map[int32]string{
	0: "UNUSED_MIME_TYPE",
	1: "APPLICATION_OCTET_STREAM",
	2: "TEXT_HTML",
}

var Response_Headers_Content_Type_Message_Common_MIME_Types_value = map[string]int32{
	"UNUSED_MIME_TYPE":         0,
	"APPLICATION_OCTET_STREAM": 1,
	"TEXT_HTML":                2,
}

func (x Response_Headers_Content_Type_Message_Common_MIME_Types) String() string {
	return proto.EnumName(Response_Headers_Content_Type_Message_Common_MIME_Types_name, int32(x))
}

func (Response_Headers_Content_Type_Message_Common_MIME_Types) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{5, 0, 1, 0}
}

type Response_Headers_Set_Cookie_Message_SameSite_Value int32

const (
	Response_Headers_Set_Cookie_Message_UNUSED_SAMESITE_VALUE Response_Headers_Set_Cookie_Message_SameSite_Value = 0
	Response_Headers_Set_Cookie_Message_STRICT                Response_Headers_Set_Cookie_Message_SameSite_Value = 1
	Response_Headers_Set_Cookie_Message_LAX                   Response_Headers_Set_Cookie_Message_SameSite_Value = 2
	Response_Headers_Set_Cookie_Message_NONE                  Response_Headers_Set_Cookie_Message_SameSite_Value = 3
)

var Response_Headers_Set_Cookie_Message_SameSite_Value_name = map[int32]string{
	0: "UNUSED_SAMESITE_VALUE",
	1: "STRICT",
	2: "LAX",
	3: "NONE",
}

var Response_Headers_Set_Cookie_Message_SameSite_Value_value = map[string]int32{
	"UNUSED_SAMESITE_VALUE": 0,
	"STRICT":                1,
	"LAX":                   2,
	"NONE":                  3,
}

func (x Response_Headers_Set_Cookie_Message_SameSite_Value) String() string {
	return proto.EnumName(Response_Headers_Set_Cookie_Message_SameSite_Value_name, int32(x))
}

func (Response_Headers_Set_Cookie_Message_SameSite_Value) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{5, 0, 2, 0}
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{0}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// for use in oneof's only
type StringList struct {
	Strings              []string `protobuf:"bytes,1,rep,name=Strings,proto3" json:"Strings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringList) Reset()         { *m = StringList{} }
func (m *StringList) String() string { return proto.CompactTextString(m) }
func (*StringList) ProtoMessage()    {}
func (*StringList) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{1}
}

func (m *StringList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringList.Unmarshal(m, b)
}
func (m *StringList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringList.Marshal(b, m, deterministic)
}
func (m *StringList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringList.Merge(m, src)
}
func (m *StringList) XXX_Size() int {
	return xxx_messageInfo_StringList.Size(m)
}
func (m *StringList) XXX_DiscardUnknown() {
	xxx_messageInfo_StringList.DiscardUnknown(m)
}

var xxx_messageInfo_StringList proto.InternalMessageInfo

func (m *StringList) GetStrings() []string {
	if m != nil {
		return m.Strings
	}
	return nil
}

type Cache_Control_Request struct {
	Directive            Cache_Control_Request_Directives `protobuf:"varint,1,opt,name=Directive,proto3,enum=web.Cache_Control_Request_Directives" json:"Directive,omitempty"`
	Seconds              uint64                           `protobuf:"varint,2,opt,name=Seconds,proto3" json:"Seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *Cache_Control_Request) Reset()         { *m = Cache_Control_Request{} }
func (m *Cache_Control_Request) String() string { return proto.CompactTextString(m) }
func (*Cache_Control_Request) ProtoMessage()    {}
func (*Cache_Control_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{2}
}

func (m *Cache_Control_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cache_Control_Request.Unmarshal(m, b)
}
func (m *Cache_Control_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cache_Control_Request.Marshal(b, m, deterministic)
}
func (m *Cache_Control_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cache_Control_Request.Merge(m, src)
}
func (m *Cache_Control_Request) XXX_Size() int {
	return xxx_messageInfo_Cache_Control_Request.Size(m)
}
func (m *Cache_Control_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Cache_Control_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Cache_Control_Request proto.InternalMessageInfo

func (m *Cache_Control_Request) GetDirective() Cache_Control_Request_Directives {
	if m != nil {
		return m.Directive
	}
	return Cache_Control_Request_UNUSED_DIRECTIVE
}

func (m *Cache_Control_Request) GetSeconds() uint64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

type Cache_Control_Response struct {
	Directive            Cache_Control_Response_Directives `protobuf:"varint,1,opt,name=Directive,proto3,enum=web.Cache_Control_Response_Directives" json:"Directive,omitempty"`
	Seconds              uint64                            `protobuf:"varint,2,opt,name=Seconds,proto3" json:"Seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *Cache_Control_Response) Reset()         { *m = Cache_Control_Response{} }
func (m *Cache_Control_Response) String() string { return proto.CompactTextString(m) }
func (*Cache_Control_Response) ProtoMessage()    {}
func (*Cache_Control_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{3}
}

func (m *Cache_Control_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cache_Control_Response.Unmarshal(m, b)
}
func (m *Cache_Control_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cache_Control_Response.Marshal(b, m, deterministic)
}
func (m *Cache_Control_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cache_Control_Response.Merge(m, src)
}
func (m *Cache_Control_Response) XXX_Size() int {
	return xxx_messageInfo_Cache_Control_Response.Size(m)
}
func (m *Cache_Control_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Cache_Control_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Cache_Control_Response proto.InternalMessageInfo

func (m *Cache_Control_Response) GetDirective() Cache_Control_Response_Directives {
	if m != nil {
		return m.Directive
	}
	return Cache_Control_Response_UNUSED_DIRECTIVE
}

func (m *Cache_Control_Response) GetSeconds() uint64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

type Request struct {
	Method Request_Method `protobuf:"varint,1,opt,name=method,proto3,enum=web.Request_Method" json:"method,omitempty"`
	// TODO: separate absolute vs. relative?
	//
	// Types that are valid to be assigned to URI:
	//	*Request_URI_Wildcard
	//	*Request_URI_String
	URI                  isRequest_URI    `protobuf_oneof:"URI"`
	Query                []*KeyValue      `protobuf:"bytes,4,rep,name=query,proto3" json:"query,omitempty"`
	Headers              *Request_Headers `protobuf:"bytes,5,opt,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{4}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMethod() Request_Method {
	if m != nil {
		return m.Method
	}
	return Request_UNUSED_METHOD
}

type isRequest_URI interface {
	isRequest_URI()
}

type Request_URI_Wildcard struct {
	URI_Wildcard Wildcard `protobuf:"varint,2,opt,name=URI_Wildcard,json=URIWildcard,proto3,enum=web.Wildcard,oneof"`
}

type Request_URI_String struct {
	URI_String string `protobuf:"bytes,3,opt,name=URI_String,json=URIString,proto3,oneof"`
}

func (*Request_URI_Wildcard) isRequest_URI() {}

func (*Request_URI_String) isRequest_URI() {}

func (m *Request) GetURI() isRequest_URI {
	if m != nil {
		return m.URI
	}
	return nil
}

func (m *Request) GetURI_Wildcard() Wildcard {
	if x, ok := m.GetURI().(*Request_URI_Wildcard); ok {
		return x.URI_Wildcard
	}
	return Wildcard_STAR
}

func (m *Request) GetURI_String() string {
	if x, ok := m.GetURI().(*Request_URI_String); ok {
		return x.URI_String
	}
	return ""
}

func (m *Request) GetQuery() []*KeyValue {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *Request) GetHeaders() *Request_Headers {
	if m != nil {
		return m.Headers
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Request) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Request_URI_Wildcard)(nil),
		(*Request_URI_String)(nil),
	}
}

type Request_Headers struct {
	Accept                         string               `protobuf:"bytes,1,opt,name=Accept,proto3" json:"Accept,omitempty"`
	Accept_Charset                 string               `protobuf:"bytes,2,opt,name=Accept_Charset,json=AcceptCharset,proto3" json:"Accept_Charset,omitempty"`
	Accept_Datetime                string               `protobuf:"bytes,3,opt,name=Accept_Datetime,json=AcceptDatetime,proto3" json:"Accept_Datetime,omitempty"`
	Accept_Encoding                string               `protobuf:"bytes,4,opt,name=Accept_Encoding,json=AcceptEncoding,proto3" json:"Accept_Encoding,omitempty"`
	Accept_Language                string               `protobuf:"bytes,5,opt,name=Accept_Language,json=AcceptLanguage,proto3" json:"Accept_Language,omitempty"`
	Access_Control_Request_Method  Request_Method       `protobuf:"varint,6,opt,name=Access_Control_Request_Method,json=AccessControlRequestMethod,proto3,enum=web.Request_Method" json:"Access_Control_Request_Method,omitempty"`
	Access_Control_Request_Headers *Request_Headers     `protobuf:"bytes,7,opt,name=Access_Control_Request_Headers,json=AccessControlRequestHeaders,proto3" json:"Access_Control_Request_Headers,omitempty"`
	Authorization                  string               `protobuf:"bytes,8,opt,name=Authorization,proto3" json:"Authorization,omitempty"`
	Expect                         string               `protobuf:"bytes,9,opt,name=Expect,proto3" json:"Expect,omitempty"`
	Forwarded                      []*KeyValue          `protobuf:"bytes,10,rep,name=Forwarded,proto3" json:"Forwarded,omitempty"`
	From                           string               `protobuf:"bytes,11,opt,name=From,proto3" json:"From,omitempty"`
	Host                           string               `protobuf:"bytes,12,opt,name=Host,proto3" json:"Host,omitempty"`
	HTTP2_Settings                 string               `protobuf:"bytes,13,opt,name=HTTP2_Settings,json=HTTP2Settings,proto3" json:"HTTP2_Settings,omitempty"`
	If_Match                       string               `protobuf:"bytes,14,opt,name=If_Match,json=IfMatch,proto3" json:"If_Match,omitempty"`
	If_Modified_Since              *timestamp.Timestamp `protobuf:"bytes,15,opt,name=If_Modified_Since,json=IfModifiedSince,proto3" json:"If_Modified_Since,omitempty"`
	If_None_Match                  string               `protobuf:"bytes,16,opt,name=If_None_Match,json=IfNoneMatch,proto3" json:"If_None_Match,omitempty"`
	If_Range                       string               `protobuf:"bytes,17,opt,name=If_Range,json=IfRange,proto3" json:"If_Range,omitempty"`
	If_Unmodified_Since            *timestamp.Timestamp `protobuf:"bytes,18,opt,name=If_Unmodified_Since,json=IfUnmodifiedSince,proto3" json:"If_Unmodified_Since,omitempty"`
	Max_Forwards                   uint64               `protobuf:"varint,19,opt,name=Max_Forwards,json=MaxForwards,proto3" json:"Max_Forwards,omitempty"`
	Origin                         string               `protobuf:"bytes,20,opt,name=Origin,proto3" json:"Origin,omitempty"`
	Pragma                         string               `protobuf:"bytes,21,opt,name=Pragma,proto3" json:"Pragma,omitempty"`
	Proxy_Authorization            string               `protobuf:"bytes,22,opt,name=Proxy_Authorization,json=ProxyAuthorization,proto3" json:"Proxy_Authorization,omitempty"`
	// Types that are valid to be assigned to Range:
	//	*Request_Headers_Bytes
	Range                isRequest_Headers_Range                    `protobuf_oneof:"Range"`
	Referer              string                                     `protobuf:"bytes,24,opt,name=Referer,proto3" json:"Referer,omitempty"`
	TE                   []Request_Headers_Transfer_Encodings_Value `protobuf:"varint,25,rep,packed,name=TE,proto3,enum=web.Request_Headers_Transfer_Encodings_Value" json:"TE,omitempty"`
	User_Agent           string                                     `protobuf:"bytes,26,opt,name=User_Agent,json=UserAgent,proto3" json:"User_Agent,omitempty"`
	Via                  []string                                   `protobuf:"bytes,27,rep,name=Via,proto3" json:"Via,omitempty"`
	Warning              string                                     `protobuf:"bytes,28,opt,name=Warning,proto3" json:"Warning,omitempty"`
	X_Requested_With     Request_Headers_X_Requested_With_Value     `protobuf:"varint,29,opt,name=X_Requested_With,json=XRequestedWith,proto3,enum=web.Request_Headers_X_Requested_With_Value" json:"X_Requested_With,omitempty"`
	DNT                  Request_Headers_DNT_Value                  `protobuf:"varint,30,opt,name=DNT,proto3,enum=web.Request_Headers_DNT_Value" json:"DNT,omitempty"`
	Other                []*KeyValue                                `protobuf:"bytes,31,rep,name=Other,proto3" json:"Other,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *Request_Headers) Reset()         { *m = Request_Headers{} }
func (m *Request_Headers) String() string { return proto.CompactTextString(m) }
func (*Request_Headers) ProtoMessage()    {}
func (*Request_Headers) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{4, 0}
}

func (m *Request_Headers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Headers.Unmarshal(m, b)
}
func (m *Request_Headers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Headers.Marshal(b, m, deterministic)
}
func (m *Request_Headers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Headers.Merge(m, src)
}
func (m *Request_Headers) XXX_Size() int {
	return xxx_messageInfo_Request_Headers.Size(m)
}
func (m *Request_Headers) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Headers.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Headers proto.InternalMessageInfo

func (m *Request_Headers) GetAccept() string {
	if m != nil {
		return m.Accept
	}
	return ""
}

func (m *Request_Headers) GetAccept_Charset() string {
	if m != nil {
		return m.Accept_Charset
	}
	return ""
}

func (m *Request_Headers) GetAccept_Datetime() string {
	if m != nil {
		return m.Accept_Datetime
	}
	return ""
}

func (m *Request_Headers) GetAccept_Encoding() string {
	if m != nil {
		return m.Accept_Encoding
	}
	return ""
}

func (m *Request_Headers) GetAccept_Language() string {
	if m != nil {
		return m.Accept_Language
	}
	return ""
}

func (m *Request_Headers) GetAccess_Control_Request_Method() Request_Method {
	if m != nil {
		return m.Access_Control_Request_Method
	}
	return Request_UNUSED_METHOD
}

func (m *Request_Headers) GetAccess_Control_Request_Headers() *Request_Headers {
	if m != nil {
		return m.Access_Control_Request_Headers
	}
	return nil
}

func (m *Request_Headers) GetAuthorization() string {
	if m != nil {
		return m.Authorization
	}
	return ""
}

func (m *Request_Headers) GetExpect() string {
	if m != nil {
		return m.Expect
	}
	return ""
}

func (m *Request_Headers) GetForwarded() []*KeyValue {
	if m != nil {
		return m.Forwarded
	}
	return nil
}

func (m *Request_Headers) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Request_Headers) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Request_Headers) GetHTTP2_Settings() string {
	if m != nil {
		return m.HTTP2_Settings
	}
	return ""
}

func (m *Request_Headers) GetIf_Match() string {
	if m != nil {
		return m.If_Match
	}
	return ""
}

func (m *Request_Headers) GetIf_Modified_Since() *timestamp.Timestamp {
	if m != nil {
		return m.If_Modified_Since
	}
	return nil
}

func (m *Request_Headers) GetIf_None_Match() string {
	if m != nil {
		return m.If_None_Match
	}
	return ""
}

func (m *Request_Headers) GetIf_Range() string {
	if m != nil {
		return m.If_Range
	}
	return ""
}

func (m *Request_Headers) GetIf_Unmodified_Since() *timestamp.Timestamp {
	if m != nil {
		return m.If_Unmodified_Since
	}
	return nil
}

func (m *Request_Headers) GetMax_Forwards() uint64 {
	if m != nil {
		return m.Max_Forwards
	}
	return 0
}

func (m *Request_Headers) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Request_Headers) GetPragma() string {
	if m != nil {
		return m.Pragma
	}
	return ""
}

func (m *Request_Headers) GetProxy_Authorization() string {
	if m != nil {
		return m.Proxy_Authorization
	}
	return ""
}

type isRequest_Headers_Range interface {
	isRequest_Headers_Range()
}

type Request_Headers_Bytes struct {
	Bytes *Request_Headers_ByteRange `protobuf:"bytes,23,opt,name=Bytes,proto3,oneof"`
}

func (*Request_Headers_Bytes) isRequest_Headers_Range() {}

func (m *Request_Headers) GetRange() isRequest_Headers_Range {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *Request_Headers) GetBytes() *Request_Headers_ByteRange {
	if x, ok := m.GetRange().(*Request_Headers_Bytes); ok {
		return x.Bytes
	}
	return nil
}

func (m *Request_Headers) GetReferer() string {
	if m != nil {
		return m.Referer
	}
	return ""
}

func (m *Request_Headers) GetTE() []Request_Headers_Transfer_Encodings_Value {
	if m != nil {
		return m.TE
	}
	return nil
}

func (m *Request_Headers) GetUser_Agent() string {
	if m != nil {
		return m.User_Agent
	}
	return ""
}

func (m *Request_Headers) GetVia() []string {
	if m != nil {
		return m.Via
	}
	return nil
}

func (m *Request_Headers) GetWarning() string {
	if m != nil {
		return m.Warning
	}
	return ""
}

func (m *Request_Headers) GetX_Requested_With() Request_Headers_X_Requested_With_Value {
	if m != nil {
		return m.X_Requested_With
	}
	return Request_Headers_UNUSED_X_REQUESTED_WITH_VALUE
}

func (m *Request_Headers) GetDNT() Request_Headers_DNT_Value {
	if m != nil {
		return m.DNT
	}
	return Request_Headers_UNUSED_DNT_VALUE
}

func (m *Request_Headers) GetOther() []*KeyValue {
	if m != nil {
		return m.Other
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Request_Headers) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Request_Headers_Bytes)(nil),
	}
}

type Request_Headers_ByteRange struct {
	Start                uint64   `protobuf:"varint,1,opt,name=Start,proto3" json:"Start,omitempty"`
	End                  uint64   `protobuf:"varint,2,opt,name=End,proto3" json:"End,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Headers_ByteRange) Reset()         { *m = Request_Headers_ByteRange{} }
func (m *Request_Headers_ByteRange) String() string { return proto.CompactTextString(m) }
func (*Request_Headers_ByteRange) ProtoMessage()    {}
func (*Request_Headers_ByteRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{4, 0, 0}
}

func (m *Request_Headers_ByteRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Headers_ByteRange.Unmarshal(m, b)
}
func (m *Request_Headers_ByteRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Headers_ByteRange.Marshal(b, m, deterministic)
}
func (m *Request_Headers_ByteRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Headers_ByteRange.Merge(m, src)
}
func (m *Request_Headers_ByteRange) XXX_Size() int {
	return xxx_messageInfo_Request_Headers_ByteRange.Size(m)
}
func (m *Request_Headers_ByteRange) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Headers_ByteRange.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Headers_ByteRange proto.InternalMessageInfo

func (m *Request_Headers_ByteRange) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Request_Headers_ByteRange) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

type Response struct {
	Code                 Response_Code_Value `protobuf:"varint,1,opt,name=Code,proto3,enum=web.Response_Code_Value" json:"Code,omitempty"`
	Headers              *Response_Headers   `protobuf:"bytes,2,opt,name=headers,proto3" json:"headers,omitempty"`
	Body                 []byte              `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() Response_Code_Value {
	if m != nil {
		return m.Code
	}
	return Response_UNUSED_CODE
}

func (m *Response) GetHeaders() *Response_Headers {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response_Headers struct {
	// Types that are valid to be assigned to Access_Control_Allow_Origin:
	//	*Response_Headers_Access_Control_Allow_Origin_All
	//	*Response_Headers_Access_Control_Allow_Origin_Origins
	Access_Control_Allow_Origin      isResponse_Headers_Access_Control_Allow_Origin          `protobuf_oneof:"Access_Control_Allow_Origin"`
	Access_Control_Allow_Credentials Response_Headers_Access_Control_Allow_Credentials_Value `protobuf:"varint,3,opt,name=Access_Control_Allow_Credentials,json=AccessControlAllowCredentials,proto3,enum=web.Response_Headers_Access_Control_Allow_Credentials_Value" json:"Access_Control_Allow_Credentials,omitempty"`
	Access_Control_Expose_Headers    []string                                                `protobuf:"bytes,4,rep,name=Access_Control_Expose_Headers,json=AccessControlExposeHeaders,proto3" json:"Access_Control_Expose_Headers,omitempty"`
	// Types that are valid to be assigned to Alt_Svc:
	//	*Response_Headers_Alt_Svc_Clear
	//	*Response_Headers_Service
	Alt_Svc      isResponse_Headers_Alt_Svc             `protobuf_oneof:"Alt_Svc"`
	Content_Type *Response_Headers_Content_Type_Message `protobuf:"bytes,7,opt,name=Content_Type,json=ContentType,proto3" json:"Content_Type,omitempty"`
	Date         *timestamp.Timestamp                   `protobuf:"bytes,8,opt,name=Date,proto3" json:"Date,omitempty"`
	// Types that are valid to be assigned to Expires:
	//	*Response_Headers_Expires_Already
	//	*Response_Headers_Expires_Date
	Expires isResponse_Headers_Expires `protobuf_oneof:"Expires"`
	Server  string                     `protobuf:"bytes,11,opt,name=Server,proto3" json:"Server,omitempty"`
	// Types that are valid to be assigned to Vary:
	//	*Response_Headers_Vary_All
	//	*Response_Headers_Vary_Headers
	Vary                 isResponse_Headers_Vary                `protobuf_oneof:"Vary"`
	X_Frame_Options      Response_Headers_X_Frame_Options_Value `protobuf:"varint,14,opt,name=X_Frame_Options,json=XFrameOptions,proto3,enum=web.Response_Headers_X_Frame_Options_Value" json:"X_Frame_Options,omitempty"`
	X_XSS_Protection     string                                 `protobuf:"bytes,15,opt,name=X_XSS_Protection,json=XXSSProtection,proto3" json:"X_XSS_Protection,omitempty"`
	Set_Cookie           []*Response_Headers_Set_Cookie_Message `protobuf:"bytes,16,rep,name=Set_Cookie,json=SetCookie,proto3" json:"Set_Cookie,omitempty"`
	Other                []*KeyValue                            `protobuf:"bytes,17,rep,name=Other,proto3" json:"Other,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *Response_Headers) Reset()         { *m = Response_Headers{} }
func (m *Response_Headers) String() string { return proto.CompactTextString(m) }
func (*Response_Headers) ProtoMessage()    {}
func (*Response_Headers) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{5, 0}
}

func (m *Response_Headers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Headers.Unmarshal(m, b)
}
func (m *Response_Headers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Headers.Marshal(b, m, deterministic)
}
func (m *Response_Headers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Headers.Merge(m, src)
}
func (m *Response_Headers) XXX_Size() int {
	return xxx_messageInfo_Response_Headers.Size(m)
}
func (m *Response_Headers) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Headers.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Headers proto.InternalMessageInfo

type isResponse_Headers_Access_Control_Allow_Origin interface {
	isResponse_Headers_Access_Control_Allow_Origin()
}

type Response_Headers_Access_Control_Allow_Origin_All struct {
	Access_Control_Allow_Origin_All Wildcard `protobuf:"varint,1,opt,name=Access_Control_Allow_Origin_All,json=AccessControlAllowOriginAll,proto3,enum=web.Wildcard,oneof"`
}

type Response_Headers_Access_Control_Allow_Origin_Origins struct {
	Access_Control_Allow_Origin_Origins *StringList `protobuf:"bytes,2,opt,name=Access_Control_Allow_Origin_Origins,json=AccessControlAllowOriginOrigins,proto3,oneof"`
}

func (*Response_Headers_Access_Control_Allow_Origin_All) isResponse_Headers_Access_Control_Allow_Origin() {
}

func (*Response_Headers_Access_Control_Allow_Origin_Origins) isResponse_Headers_Access_Control_Allow_Origin() {
}

func (m *Response_Headers) GetAccess_Control_Allow_Origin() isResponse_Headers_Access_Control_Allow_Origin {
	if m != nil {
		return m.Access_Control_Allow_Origin
	}
	return nil
}

func (m *Response_Headers) GetAccess_Control_Allow_Origin_All() Wildcard {
	if x, ok := m.GetAccess_Control_Allow_Origin().(*Response_Headers_Access_Control_Allow_Origin_All); ok {
		return x.Access_Control_Allow_Origin_All
	}
	return Wildcard_STAR
}

func (m *Response_Headers) GetAccess_Control_Allow_Origin_Origins() *StringList {
	if x, ok := m.GetAccess_Control_Allow_Origin().(*Response_Headers_Access_Control_Allow_Origin_Origins); ok {
		return x.Access_Control_Allow_Origin_Origins
	}
	return nil
}

func (m *Response_Headers) GetAccess_Control_Allow_Credentials() Response_Headers_Access_Control_Allow_Credentials_Value {
	if m != nil {
		return m.Access_Control_Allow_Credentials
	}
	return Response_Headers_UNUSED_ACCESS_CONTROL_ALLOW_CREDENTIALS_VALUE
}

func (m *Response_Headers) GetAccess_Control_Expose_Headers() []string {
	if m != nil {
		return m.Access_Control_Expose_Headers
	}
	return nil
}

type isResponse_Headers_Alt_Svc interface {
	isResponse_Headers_Alt_Svc()
}

type Response_Headers_Alt_Svc_Clear struct {
	Alt_Svc_Clear Clear `protobuf:"varint,5,opt,name=Alt_Svc_Clear,json=AltSvcClear,proto3,enum=web.Clear,oneof"`
}

type Response_Headers_Service struct {
	Service *Response_Headers_Alt_Svc_Message `protobuf:"bytes,6,opt,name=Service,proto3,oneof"`
}

func (*Response_Headers_Alt_Svc_Clear) isResponse_Headers_Alt_Svc() {}

func (*Response_Headers_Service) isResponse_Headers_Alt_Svc() {}

func (m *Response_Headers) GetAlt_Svc() isResponse_Headers_Alt_Svc {
	if m != nil {
		return m.Alt_Svc
	}
	return nil
}

func (m *Response_Headers) GetAlt_Svc_Clear() Clear {
	if x, ok := m.GetAlt_Svc().(*Response_Headers_Alt_Svc_Clear); ok {
		return x.Alt_Svc_Clear
	}
	return Clear_CLEAR
}

func (m *Response_Headers) GetService() *Response_Headers_Alt_Svc_Message {
	if x, ok := m.GetAlt_Svc().(*Response_Headers_Service); ok {
		return x.Service
	}
	return nil
}

func (m *Response_Headers) GetContent_Type() *Response_Headers_Content_Type_Message {
	if m != nil {
		return m.Content_Type
	}
	return nil
}

func (m *Response_Headers) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

type isResponse_Headers_Expires interface {
	isResponse_Headers_Expires()
}

type Response_Headers_Expires_Already struct {
	Expires_Already Already `protobuf:"varint,9,opt,name=Expires_Already,json=ExpiresAlready,proto3,enum=web.Already,oneof"`
}

type Response_Headers_Expires_Date struct {
	Expires_Date *timestamp.Timestamp `protobuf:"bytes,10,opt,name=Expires_Date,json=ExpiresDate,proto3,oneof"`
}

func (*Response_Headers_Expires_Already) isResponse_Headers_Expires() {}

func (*Response_Headers_Expires_Date) isResponse_Headers_Expires() {}

func (m *Response_Headers) GetExpires() isResponse_Headers_Expires {
	if m != nil {
		return m.Expires
	}
	return nil
}

func (m *Response_Headers) GetExpires_Already() Already {
	if x, ok := m.GetExpires().(*Response_Headers_Expires_Already); ok {
		return x.Expires_Already
	}
	return Already_ALREADY
}

func (m *Response_Headers) GetExpires_Date() *timestamp.Timestamp {
	if x, ok := m.GetExpires().(*Response_Headers_Expires_Date); ok {
		return x.Expires_Date
	}
	return nil
}

func (m *Response_Headers) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

type isResponse_Headers_Vary interface {
	isResponse_Headers_Vary()
}

type Response_Headers_Vary_All struct {
	Vary_All Wildcard `protobuf:"varint,12,opt,name=Vary_All,json=VaryAll,proto3,enum=web.Wildcard,oneof"`
}

type Response_Headers_Vary_Headers struct {
	Vary_Headers *StringList `protobuf:"bytes,13,opt,name=Vary_Headers,json=VaryHeaders,proto3,oneof"`
}

func (*Response_Headers_Vary_All) isResponse_Headers_Vary() {}

func (*Response_Headers_Vary_Headers) isResponse_Headers_Vary() {}

func (m *Response_Headers) GetVary() isResponse_Headers_Vary {
	if m != nil {
		return m.Vary
	}
	return nil
}

func (m *Response_Headers) GetVary_All() Wildcard {
	if x, ok := m.GetVary().(*Response_Headers_Vary_All); ok {
		return x.Vary_All
	}
	return Wildcard_STAR
}

func (m *Response_Headers) GetVary_Headers() *StringList {
	if x, ok := m.GetVary().(*Response_Headers_Vary_Headers); ok {
		return x.Vary_Headers
	}
	return nil
}

func (m *Response_Headers) GetX_Frame_Options() Response_Headers_X_Frame_Options_Value {
	if m != nil {
		return m.X_Frame_Options
	}
	return Response_Headers_UNUSED_X_FRAME_OPTIONS_VALUE
}

func (m *Response_Headers) GetX_XSS_Protection() string {
	if m != nil {
		return m.X_XSS_Protection
	}
	return ""
}

func (m *Response_Headers) GetSet_Cookie() []*Response_Headers_Set_Cookie_Message {
	if m != nil {
		return m.Set_Cookie
	}
	return nil
}

func (m *Response_Headers) GetOther() []*KeyValue {
	if m != nil {
		return m.Other
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response_Headers) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_Headers_Access_Control_Allow_Origin_All)(nil),
		(*Response_Headers_Access_Control_Allow_Origin_Origins)(nil),
		(*Response_Headers_Alt_Svc_Clear)(nil),
		(*Response_Headers_Service)(nil),
		(*Response_Headers_Expires_Already)(nil),
		(*Response_Headers_Expires_Date)(nil),
		(*Response_Headers_Vary_All)(nil),
		(*Response_Headers_Vary_Headers)(nil),
	}
}

type Response_Headers_Alt_Svc_Message struct {
	Services             []*Response_Headers_Alt_Svc_Message_Service `protobuf:"bytes,1,rep,name=Services,proto3" json:"Services,omitempty"`
	Max_Age              uint64                                      `protobuf:"varint,2,opt,name=Max_Age,json=MaxAge,proto3" json:"Max_Age,omitempty"`
	Persist              bool                                        `protobuf:"varint,3,opt,name=Persist,proto3" json:"Persist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *Response_Headers_Alt_Svc_Message) Reset()         { *m = Response_Headers_Alt_Svc_Message{} }
func (m *Response_Headers_Alt_Svc_Message) String() string { return proto.CompactTextString(m) }
func (*Response_Headers_Alt_Svc_Message) ProtoMessage()    {}
func (*Response_Headers_Alt_Svc_Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{5, 0, 0}
}

func (m *Response_Headers_Alt_Svc_Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Headers_Alt_Svc_Message.Unmarshal(m, b)
}
func (m *Response_Headers_Alt_Svc_Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Headers_Alt_Svc_Message.Marshal(b, m, deterministic)
}
func (m *Response_Headers_Alt_Svc_Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Headers_Alt_Svc_Message.Merge(m, src)
}
func (m *Response_Headers_Alt_Svc_Message) XXX_Size() int {
	return xxx_messageInfo_Response_Headers_Alt_Svc_Message.Size(m)
}
func (m *Response_Headers_Alt_Svc_Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Headers_Alt_Svc_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Headers_Alt_Svc_Message proto.InternalMessageInfo

func (m *Response_Headers_Alt_Svc_Message) GetServices() []*Response_Headers_Alt_Svc_Message_Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Response_Headers_Alt_Svc_Message) GetMax_Age() uint64 {
	if m != nil {
		return m.Max_Age
	}
	return 0
}

func (m *Response_Headers_Alt_Svc_Message) GetPersist() bool {
	if m != nil {
		return m.Persist
	}
	return false
}

type Response_Headers_Alt_Svc_Message_Service struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Host_Name            string   `protobuf:"bytes,2,opt,name=Host_Name,json=HostName,proto3" json:"Host_Name,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Headers_Alt_Svc_Message_Service) Reset() {
	*m = Response_Headers_Alt_Svc_Message_Service{}
}
func (m *Response_Headers_Alt_Svc_Message_Service) String() string { return proto.CompactTextString(m) }
func (*Response_Headers_Alt_Svc_Message_Service) ProtoMessage()    {}
func (*Response_Headers_Alt_Svc_Message_Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{5, 0, 0, 0}
}

func (m *Response_Headers_Alt_Svc_Message_Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Headers_Alt_Svc_Message_Service.Unmarshal(m, b)
}
func (m *Response_Headers_Alt_Svc_Message_Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Headers_Alt_Svc_Message_Service.Marshal(b, m, deterministic)
}
func (m *Response_Headers_Alt_Svc_Message_Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Headers_Alt_Svc_Message_Service.Merge(m, src)
}
func (m *Response_Headers_Alt_Svc_Message_Service) XXX_Size() int {
	return xxx_messageInfo_Response_Headers_Alt_Svc_Message_Service.Size(m)
}
func (m *Response_Headers_Alt_Svc_Message_Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Headers_Alt_Svc_Message_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Headers_Alt_Svc_Message_Service proto.InternalMessageInfo

func (m *Response_Headers_Alt_Svc_Message_Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response_Headers_Alt_Svc_Message_Service) GetHost_Name() string {
	if m != nil {
		return m.Host_Name
	}
	return ""
}

func (m *Response_Headers_Alt_Svc_Message_Service) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Response_Headers_Content_Type_Message struct {
	// Types that are valid to be assigned to Content_Type_Message:
	//	*Response_Headers_Content_Type_Message_Common_MIME_Type
	//	*Response_Headers_Content_Type_Message_Other
	Content_Type_Message isResponse_Headers_Content_Type_Message_Content_Type_Message `protobuf_oneof:"Content_Type_Message"`
	Parameter            *KeyValue                                                    `protobuf:"bytes,3,opt,name=Parameter,proto3" json:"Parameter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                     `json:"-"`
	XXX_unrecognized     []byte                                                       `json:"-"`
	XXX_sizecache        int32                                                        `json:"-"`
}

func (m *Response_Headers_Content_Type_Message) Reset()         { *m = Response_Headers_Content_Type_Message{} }
func (m *Response_Headers_Content_Type_Message) String() string { return proto.CompactTextString(m) }
func (*Response_Headers_Content_Type_Message) ProtoMessage()    {}
func (*Response_Headers_Content_Type_Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{5, 0, 1}
}

func (m *Response_Headers_Content_Type_Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Headers_Content_Type_Message.Unmarshal(m, b)
}
func (m *Response_Headers_Content_Type_Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Headers_Content_Type_Message.Marshal(b, m, deterministic)
}
func (m *Response_Headers_Content_Type_Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Headers_Content_Type_Message.Merge(m, src)
}
func (m *Response_Headers_Content_Type_Message) XXX_Size() int {
	return xxx_messageInfo_Response_Headers_Content_Type_Message.Size(m)
}
func (m *Response_Headers_Content_Type_Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Headers_Content_Type_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Headers_Content_Type_Message proto.InternalMessageInfo

type isResponse_Headers_Content_Type_Message_Content_Type_Message interface {
	isResponse_Headers_Content_Type_Message_Content_Type_Message()
}

type Response_Headers_Content_Type_Message_Common_MIME_Type struct {
	Common_MIME_Type Response_Headers_Content_Type_Message_Common_MIME_Types `protobuf:"varint,1,opt,name=Common_MIME_Type,json=CommonMIMEType,proto3,enum=web.Response_Headers_Content_Type_Message_Common_MIME_Types,oneof"`
}

type Response_Headers_Content_Type_Message_Other struct {
	Other string `protobuf:"bytes,2,opt,name=Other,proto3,oneof"`
}

func (*Response_Headers_Content_Type_Message_Common_MIME_Type) isResponse_Headers_Content_Type_Message_Content_Type_Message() {
}

func (*Response_Headers_Content_Type_Message_Other) isResponse_Headers_Content_Type_Message_Content_Type_Message() {
}

func (m *Response_Headers_Content_Type_Message) GetContent_Type_Message() isResponse_Headers_Content_Type_Message_Content_Type_Message {
	if m != nil {
		return m.Content_Type_Message
	}
	return nil
}

func (m *Response_Headers_Content_Type_Message) GetCommon_MIME_Type() Response_Headers_Content_Type_Message_Common_MIME_Types {
	if x, ok := m.GetContent_Type_Message().(*Response_Headers_Content_Type_Message_Common_MIME_Type); ok {
		return x.Common_MIME_Type
	}
	return Response_Headers_Content_Type_Message_UNUSED_MIME_TYPE
}

func (m *Response_Headers_Content_Type_Message) GetOther() string {
	if x, ok := m.GetContent_Type_Message().(*Response_Headers_Content_Type_Message_Other); ok {
		return x.Other
	}
	return ""
}

func (m *Response_Headers_Content_Type_Message) GetParameter() *KeyValue {
	if m != nil {
		return m.Parameter
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response_Headers_Content_Type_Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_Headers_Content_Type_Message_Common_MIME_Type)(nil),
		(*Response_Headers_Content_Type_Message_Other)(nil),
	}
}

type Response_Headers_Set_Cookie_Message struct {
	Name                 string                                             `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Value                string                                             `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Expires              *timestamp.Timestamp                               `protobuf:"bytes,3,opt,name=Expires,proto3" json:"Expires,omitempty"`
	Max_Age              int64                                              `protobuf:"varint,4,opt,name=Max_Age,json=MaxAge,proto3" json:"Max_Age,omitempty"`
	Domain               string                                             `protobuf:"bytes,5,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Path                 string                                             `protobuf:"bytes,6,opt,name=Path,proto3" json:"Path,omitempty"`
	Secure               bool                                               `protobuf:"varint,7,opt,name=Secure,proto3" json:"Secure,omitempty"`
	HttpOnly             bool                                               `protobuf:"varint,8,opt,name=HttpOnly,proto3" json:"HttpOnly,omitempty"`
	SameSite             Response_Headers_Set_Cookie_Message_SameSite_Value `protobuf:"varint,9,opt,name=SameSite,proto3,enum=web.Response_Headers_Set_Cookie_Message_SameSite_Value" json:"SameSite,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *Response_Headers_Set_Cookie_Message) Reset()         { *m = Response_Headers_Set_Cookie_Message{} }
func (m *Response_Headers_Set_Cookie_Message) String() string { return proto.CompactTextString(m) }
func (*Response_Headers_Set_Cookie_Message) ProtoMessage()    {}
func (*Response_Headers_Set_Cookie_Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{5, 0, 2}
}

func (m *Response_Headers_Set_Cookie_Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Headers_Set_Cookie_Message.Unmarshal(m, b)
}
func (m *Response_Headers_Set_Cookie_Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Headers_Set_Cookie_Message.Marshal(b, m, deterministic)
}
func (m *Response_Headers_Set_Cookie_Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Headers_Set_Cookie_Message.Merge(m, src)
}
func (m *Response_Headers_Set_Cookie_Message) XXX_Size() int {
	return xxx_messageInfo_Response_Headers_Set_Cookie_Message.Size(m)
}
func (m *Response_Headers_Set_Cookie_Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Headers_Set_Cookie_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Headers_Set_Cookie_Message proto.InternalMessageInfo

func (m *Response_Headers_Set_Cookie_Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response_Headers_Set_Cookie_Message) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Response_Headers_Set_Cookie_Message) GetExpires() *timestamp.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

func (m *Response_Headers_Set_Cookie_Message) GetMax_Age() int64 {
	if m != nil {
		return m.Max_Age
	}
	return 0
}

func (m *Response_Headers_Set_Cookie_Message) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Response_Headers_Set_Cookie_Message) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Response_Headers_Set_Cookie_Message) GetSecure() bool {
	if m != nil {
		return m.Secure
	}
	return false
}

func (m *Response_Headers_Set_Cookie_Message) GetHttpOnly() bool {
	if m != nil {
		return m.HttpOnly
	}
	return false
}

func (m *Response_Headers_Set_Cookie_Message) GetSameSite() Response_Headers_Set_Cookie_Message_SameSite_Value {
	if m != nil {
		return m.SameSite
	}
	return Response_Headers_Set_Cookie_Message_UNUSED_SAMESITE_VALUE
}

func init() {
	proto.RegisterEnum("web.Wildcard", Wildcard_name, Wildcard_value)
	proto.RegisterEnum("web.Already", Already_name, Already_value)
	proto.RegisterEnum("web.Clear", Clear_name, Clear_value)
	proto.RegisterEnum("web.Cache_Control_Request_Directives", Cache_Control_Request_Directives_name, Cache_Control_Request_Directives_value)
	proto.RegisterEnum("web.Cache_Control_Response_Directives", Cache_Control_Response_Directives_name, Cache_Control_Response_Directives_value)
	proto.RegisterEnum("web.Request_Method", Request_Method_name, Request_Method_value)
	proto.RegisterEnum("web.Request_Headers_Transfer_Encodings_Value", Request_Headers_Transfer_Encodings_Value_name, Request_Headers_Transfer_Encodings_Value_value)
	proto.RegisterEnum("web.Request_Headers_X_Requested_With_Value", Request_Headers_X_Requested_With_Value_name, Request_Headers_X_Requested_With_Value_value)
	proto.RegisterEnum("web.Request_Headers_DNT_Value", Request_Headers_DNT_Value_name, Request_Headers_DNT_Value_value)
	proto.RegisterEnum("web.Response_Code_Value", Response_Code_Value_name, Response_Code_Value_value)
	proto.RegisterEnum("web.Response_Headers_Access_Control_Allow_Credentials_Value", Response_Headers_Access_Control_Allow_Credentials_Value_name, Response_Headers_Access_Control_Allow_Credentials_Value_value)
	proto.RegisterEnum("web.Response_Headers_X_Frame_Options_Value", Response_Headers_X_Frame_Options_Value_name, Response_Headers_X_Frame_Options_Value_value)
	proto.RegisterEnum("web.Response_Headers_Content_Type_Message_Common_MIME_Types", Response_Headers_Content_Type_Message_Common_MIME_Types_name, Response_Headers_Content_Type_Message_Common_MIME_Types_value)
	proto.RegisterEnum("web.Response_Headers_Set_Cookie_Message_SameSite_Value", Response_Headers_Set_Cookie_Message_SameSite_Value_name, Response_Headers_Set_Cookie_Message_SameSite_Value_value)
	proto.RegisterType((*KeyValue)(nil), "web.KeyValue")
	proto.RegisterType((*StringList)(nil), "web.StringList")
	proto.RegisterType((*Cache_Control_Request)(nil), "web.Cache_Control_Request")
	proto.RegisterType((*Cache_Control_Response)(nil), "web.Cache_Control_Response")
	proto.RegisterType((*Request)(nil), "web.Request")
	proto.RegisterType((*Request_Headers)(nil), "web.Request.Headers")
	proto.RegisterType((*Request_Headers_ByteRange)(nil), "web.Request.Headers.ByteRange")
	proto.RegisterType((*Response)(nil), "web.Response")
	proto.RegisterType((*Response_Headers)(nil), "web.Response.Headers")
	proto.RegisterType((*Response_Headers_Alt_Svc_Message)(nil), "web.Response.Headers.Alt_Svc_Message")
	proto.RegisterType((*Response_Headers_Alt_Svc_Message_Service)(nil), "web.Response.Headers.Alt_Svc_Message.Service")
	proto.RegisterType((*Response_Headers_Content_Type_Message)(nil), "web.Response.Headers.Content_Type_Message")
	proto.RegisterType((*Response_Headers_Set_Cookie_Message)(nil), "web.Response.Headers.Set_Cookie_Message")
}

func init() { proto.RegisterFile("web.proto", fileDescriptor_461bb3ac99194e85) }

var fileDescriptor_461bb3ac99194e85 = []byte{
	// 2250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xcd, 0x72, 0xdb, 0xc8,
	0xf1, 0x17, 0xbf, 0xc9, 0x26, 0x45, 0x41, 0x23, 0x59, 0x8b, 0x95, 0x2d, 0x4b, 0x4b, 0xff, 0xd7,
	0x7f, 0x95, 0x9d, 0xa5, 0x37, 0xda, 0xad, 0xec, 0x65, 0x53, 0x29, 0x08, 0x1c, 0x99, 0x58, 0x93,
	0x00, 0x33, 0x00, 0x65, 0xea, 0x34, 0x05, 0x93, 0x23, 0x8a, 0x15, 0x92, 0xd0, 0x02, 0x90, 0x2d,
	0xe5, 0x9e, 0xaa, 0x9c, 0x92, 0x3c, 0x45, 0x0e, 0xb9, 0xe4, 0x94, 0xaa, 0x3c, 0xc2, 0xbe, 0x45,
	0x5e, 0x25, 0x35, 0x1f, 0x20, 0x29, 0x09, 0x96, 0x9d, 0x13, 0xa7, 0x7f, 0xd3, 0xdd, 0xd3, 0xd3,
	0xd3, 0x5f, 0x20, 0x54, 0x3e, 0xb0, 0x77, 0xcd, 0xcb, 0x30, 0x88, 0x03, 0x94, 0xfb, 0xc0, 0xde,
	0xed, 0xee, 0x8f, 0x83, 0x60, 0x3c, 0x65, 0xaf, 0x04, 0xf4, 0xee, 0xea, 0xfc, 0x55, 0x3c, 0x99,
	0xb1, 0x28, 0xf6, 0x67, 0x97, 0x92, 0xab, 0x71, 0x04, 0xe5, 0x37, 0xec, 0xe6, 0xd4, 0x9f, 0x5e,
	0x31, 0xa4, 0x41, 0xee, 0x0d, 0xbb, 0xd1, 0x33, 0x07, 0x99, 0xc3, 0x0a, 0xe1, 0x4b, 0xb4, 0x0d,
	0x05, 0xb1, 0xa5, 0x67, 0x05, 0x26, 0x89, 0xc6, 0x73, 0x00, 0x37, 0x0e, 0x27, 0xf3, 0x71, 0x67,
	0x12, 0xc5, 0x48, 0x87, 0x92, 0xa4, 0x22, 0x3d, 0x73, 0x90, 0x3b, 0xac, 0x90, 0x84, 0x6c, 0xfc,
	0x39, 0x0b, 0x8f, 0x4c, 0x7f, 0x78, 0xc1, 0xa8, 0x19, 0xcc, 0xe3, 0x30, 0x98, 0x52, 0xc2, 0x7e,
	0xbe, 0x62, 0x51, 0x8c, 0x4c, 0xa8, 0xb4, 0x26, 0x21, 0x1b, 0xc6, 0x93, 0xf7, 0x4c, 0x9c, 0x57,
	0x3f, 0xfa, 0xba, 0xc9, 0x4d, 0x4f, 0x65, 0x6f, 0x2e, 0x78, 0x23, 0xb2, 0x94, 0x13, 0x07, 0xb3,
	0x61, 0x30, 0x1f, 0x45, 0xc2, 0xbc, 0x3c, 0x49, 0xc8, 0xc6, 0x5f, 0x33, 0x00, 0x4b, 0x19, 0xb4,
	0x0d, 0x5a, 0xdf, 0xee, 0xbb, 0xb8, 0x45, 0x5b, 0x16, 0xc1, 0xa6, 0x67, 0x9d, 0x62, 0x6d, 0x0d,
	0x55, 0xa1, 0xd4, 0x35, 0x06, 0xd4, 0x78, 0x8d, 0xb5, 0x0c, 0x5a, 0x87, 0x0a, 0x27, 0x5c, 0xcf,
	0xe8, 0x60, 0x2d, 0x2b, 0x48, 0xcb, 0xa6, 0x27, 0x04, 0xbb, 0x6d, 0x2d, 0x87, 0x6a, 0x50, 0xb6,
	0x1d, 0x6a, 0x1a, 0x66, 0x1b, 0x6b, 0x79, 0x45, 0xb9, 0x9e, 0x43, 0xb0, 0x56, 0x40, 0x1a, 0xd4,
	0x6c, 0x87, 0x7a, 0xc4, 0xb0, 0xdd, 0x13, 0x87, 0x74, 0xb5, 0x22, 0x42, 0x50, 0x77, 0xec, 0xce,
	0x19, 0x75, 0x4e, 0xa4, 0x48, 0x4b, 0x2b, 0x35, 0xfe, 0x91, 0x85, 0x9d, 0xbb, 0x77, 0x8b, 0x2e,
	0x83, 0x79, 0xc4, 0x50, 0xeb, 0xbe, 0x2f, 0x9e, 0xa7, 0xfa, 0x42, 0xf2, 0xff, 0xcf, 0xce, 0xf8,
	0xe7, 0xe7, 0x38, 0x63, 0x0b, 0x36, 0xba, 0x7d, 0xd7, 0xa3, 0x04, 0x9f, 0x1a, 0x1d, 0xab, 0x65,
	0x78, 0xdc, 0x29, 0xab, 0xd7, 0xce, 0xde, 0xba, 0x76, 0xee, 0xde, 0xb5, 0xf3, 0x08, 0xa0, 0xd8,
	0xeb, 0x1f, 0x77, 0x2c, 0x53, 0x2b, 0x70, 0xdf, 0xf6, 0x88, 0x75, 0xca, 0xd5, 0x14, 0xf9, 0x89,
	0x3d, 0xe2, 0x0c, 0xce, 0x56, 0x95, 0x97, 0x56, 0xdd, 0x5f, 0xe6, 0xba, 0x5d, 0xda, 0x35, 0x06,
	0x9c, 0xaa, 0x34, 0xfe, 0xbe, 0x01, 0xa5, 0x24, 0x52, 0x5e, 0x42, 0x71, 0xc6, 0xe2, 0x8b, 0x60,
	0xa4, 0x5c, 0xb3, 0x25, 0x5c, 0x93, 0x04, 0x46, 0x57, 0x6c, 0x11, 0xc5, 0x82, 0x8e, 0xa0, 0xd6,
	0x27, 0x16, 0x7d, 0x3b, 0x99, 0x8e, 0x86, 0x7e, 0x38, 0x12, 0x9e, 0xa8, 0x1f, 0xad, 0x0b, 0x91,
	0x04, 0x6c, 0xaf, 0x91, 0x6a, 0x9f, 0x58, 0x09, 0x89, 0xf6, 0x01, 0xb8, 0x8c, 0x8c, 0x59, 0x3d,
	0xc7, 0xe3, 0xbc, 0xbd, 0x46, 0x2a, 0x7d, 0x62, 0x49, 0x08, 0x3d, 0x83, 0xc2, 0xcf, 0x57, 0x2c,
	0xbc, 0xd1, 0xf3, 0x07, 0xb9, 0xc3, 0xaa, 0xd2, 0x96, 0xe4, 0x0c, 0x91, 0x7b, 0xa8, 0x09, 0xa5,
	0x0b, 0xe6, 0x8f, 0x58, 0x18, 0xe9, 0x85, 0x83, 0xcc, 0x61, 0xf5, 0x68, 0xfb, 0x96, 0x9d, 0x6d,
	0xb9, 0x47, 0x12, 0xa6, 0xdd, 0x5f, 0x6a, 0x50, 0x52, 0x20, 0xda, 0x81, 0xa2, 0x31, 0x1c, 0xb2,
	0xcb, 0x58, 0x65, 0x9e, 0xa2, 0xd0, 0xd7, 0x50, 0x97, 0x2b, 0x6a, 0x5e, 0xf8, 0x61, 0xc4, 0x62,
	0x95, 0x85, 0xeb, 0x12, 0x55, 0x20, 0xfa, 0x7f, 0xd8, 0x50, 0x6c, 0x2d, 0x3f, 0x66, 0x3c, 0xbf,
	0xe5, 0x2d, 0x88, 0x92, 0x4e, 0xd0, 0x15, 0x46, 0x3c, 0x1f, 0x06, 0x23, 0x7e, 0xdd, 0xfc, 0x2a,
	0x63, 0x82, 0xae, 0x30, 0x76, 0xfc, 0xf9, 0xf8, 0xca, 0x1f, 0x33, 0x71, 0xa9, 0x05, 0x63, 0x82,
	0xa2, 0x53, 0xd8, 0xe3, 0x48, 0x14, 0xdd, 0xcd, 0x58, 0x2a, 0x1f, 0x46, 0x2f, 0x7e, 0xfc, 0xcd,
	0x76, 0xa5, 0xa4, 0x12, 0x54, 0x9b, 0x72, 0x0f, 0x9d, 0xc1, 0xd3, 0x8f, 0xe8, 0x55, 0x3e, 0xd3,
	0x4b, 0x0f, 0x38, 0xf9, 0x71, 0x9a, 0xe6, 0xc4, 0xd9, 0xff, 0x07, 0xeb, 0xc6, 0x55, 0x7c, 0x11,
	0x84, 0x93, 0x3f, 0xfa, 0xf1, 0x24, 0x98, 0xeb, 0x65, 0xe5, 0xd3, 0x55, 0x90, 0x3f, 0x09, 0xbe,
	0xbe, 0x64, 0xc3, 0x58, 0xaf, 0xc8, 0x27, 0x91, 0x14, 0x7a, 0x09, 0x95, 0x93, 0x20, 0xfc, 0xe0,
	0x87, 0x23, 0x36, 0xd2, 0x21, 0x2d, 0x1e, 0x96, 0xfb, 0x08, 0x41, 0xfe, 0x24, 0x0c, 0x66, 0x7a,
	0x55, 0xa8, 0x10, 0x6b, 0x8e, 0xb5, 0x83, 0x28, 0xd6, 0x6b, 0x12, 0xe3, 0x6b, 0xfe, 0xce, 0x6d,
	0xcf, 0xeb, 0x1d, 0x51, 0x97, 0xc5, 0xb1, 0xa8, 0xa3, 0xeb, 0xd2, 0x26, 0x81, 0x26, 0x20, 0xfa,
	0x12, 0xca, 0xd6, 0x39, 0xed, 0xfa, 0xf1, 0xf0, 0x42, 0xaf, 0x0b, 0x86, 0x92, 0x75, 0x2e, 0x48,
	0x74, 0x02, 0x9b, 0x7c, 0x2b, 0x18, 0x4d, 0xce, 0x27, 0x6c, 0x44, 0xdd, 0xc9, 0x7c, 0xc8, 0xf4,
	0x0d, 0xe1, 0xa2, 0xdd, 0xa6, 0xec, 0x00, 0xcd, 0xa4, 0x03, 0x34, 0xbd, 0xa4, 0x03, 0x90, 0x0d,
	0xeb, 0x3c, 0x91, 0x11, 0x22, 0xa8, 0x01, 0xeb, 0xd6, 0x39, 0xb5, 0x83, 0x39, 0x53, 0xe7, 0x68,
	0xe2, 0x9c, 0xaa, 0x75, 0xce, 0x31, 0x79, 0x96, 0x34, 0x83, 0xf8, 0xf3, 0x31, 0xd3, 0x37, 0x13,
	0x33, 0x04, 0x89, 0x7e, 0x82, 0x2d, 0xeb, 0x9c, 0xf6, 0xe7, 0xb3, 0xdb, 0x86, 0xa0, 0x4f, 0x1a,
	0xb2, 0x69, 0x9d, 0x2f, 0xa5, 0xa4, 0x29, 0x5f, 0x41, 0xad, 0xeb, 0x5f, 0x53, 0xe5, 0xcd, 0x48,
	0xdf, 0x12, 0x45, 0xad, 0xda, 0xf5, 0xaf, 0x13, 0x88, 0x3f, 0x92, 0x13, 0x4e, 0xc6, 0x93, 0xb9,
	0xbe, 0x2d, 0x1f, 0x49, 0x52, 0x1c, 0xef, 0x85, 0xfe, 0x78, 0xe6, 0xeb, 0x8f, 0x24, 0x2e, 0x29,
	0xf4, 0x0a, 0xb6, 0x7a, 0x61, 0x70, 0x7d, 0x43, 0x6f, 0x07, 0xc0, 0x8e, 0x60, 0x42, 0x62, 0xeb,
	0x76, 0x14, 0xfc, 0x06, 0x0a, 0xc7, 0x37, 0x31, 0x8b, 0xf4, 0x2f, 0xc4, 0x0d, 0x9e, 0xa6, 0x45,
	0x5b, 0x93, 0x73, 0x88, 0xeb, 0xb7, 0xd7, 0x88, 0x64, 0xe7, 0xb5, 0x98, 0xb0, 0x73, 0x16, 0xb2,
	0x50, 0xd7, 0xa5, 0x87, 0x14, 0x89, 0x7e, 0x0b, 0x59, 0x0f, 0xeb, 0x5f, 0x1e, 0xe4, 0x0e, 0xeb,
	0x47, 0xdf, 0xa4, 0xaa, 0xf3, 0x42, 0x7f, 0x1e, 0x9d, 0xb3, 0x70, 0x91, 0xa3, 0x11, 0x95, 0x81,
	0x95, 0xf5, 0x30, 0xda, 0x03, 0xe8, 0x47, 0x2c, 0xa4, 0xc6, 0x98, 0xcd, 0x63, 0x7d, 0x57, 0xe8,
	0xae, 0x70, 0x44, 0x00, 0xbc, 0x7f, 0x9f, 0x4e, 0x7c, 0xfd, 0xb1, 0xe8, 0xc2, 0x7c, 0xc9, 0x2d,
	0x79, 0xeb, 0x87, 0x73, 0x9e, 0xea, 0x4f, 0xa4, 0x25, 0x8a, 0x44, 0x7d, 0xd0, 0x06, 0x49, 0x56,
	0xb1, 0x11, 0x7d, 0x3b, 0x89, 0x2f, 0xf4, 0x3d, 0x91, 0xad, 0x2f, 0x53, 0xed, 0xba, 0xcb, 0xac,
	0xac, 0xaa, 0x0f, 0x16, 0x30, 0x47, 0xd1, 0xb7, 0x90, 0x6b, 0xd9, 0x9e, 0xfe, 0x54, 0x68, 0x4a,
	0x77, 0x58, 0xcb, 0xf6, 0x94, 0x30, 0x67, 0xe5, 0xe5, 0xd5, 0x89, 0x2f, 0x58, 0xa8, 0xef, 0xa7,
	0x96, 0x57, 0xb1, 0xb7, 0xfb, 0x1d, 0x54, 0x16, 0x7e, 0xe6, 0x43, 0x89, 0x1b, 0xfb, 0xa1, 0x2c,
	0x97, 0x79, 0x22, 0x09, 0x7e, 0x79, 0x3c, 0x1f, 0xa9, 0xe6, 0xc7, 0x97, 0x8d, 0x2e, 0xe8, 0x1f,
	0xf3, 0x26, 0x7a, 0x06, 0xfb, 0xaa, 0x0b, 0xca, 0x16, 0x86, 0x09, 0xc5, 0xb6, 0xe9, 0xb4, 0x2c,
	0xfb, 0xb5, 0x4b, 0x4f, 0x8d, 0x4e, 0x9f, 0x37, 0xc5, 0x1a, 0x94, 0x3d, 0x62, 0x58, 0x1d, 0x4c,
	0x5c, 0x2d, 0xd3, 0x70, 0x60, 0x27, 0xdd, 0x09, 0xe8, 0x2b, 0xd8, 0x53, 0xca, 0x06, 0x94, 0xe0,
	0xdf, 0xf7, 0xb1, 0xeb, 0xe1, 0x16, 0x7d, 0x6b, 0x79, 0xed, 0x85, 0x2a, 0x04, 0xf5, 0x41, 0xb7,
	0xc3, 0x13, 0x5a, 0x31, 0x68, 0x99, 0xc6, 0x8f, 0x50, 0x59, 0xf8, 0x62, 0xb5, 0x2d, 0x73, 0x6c,
	0x69, 0x41, 0xcb, 0x72, 0x8d, 0xe3, 0x0e, 0x6e, 0x69, 0x19, 0xde, 0x32, 0xb1, 0x2d, 0x89, 0xec,
	0x71, 0x09, 0x0a, 0xc2, 0x1d, 0x8d, 0x10, 0x8a, 0xaa, 0x6c, 0x6e, 0xc2, 0xba, 0xd2, 0xd1, 0xc5,
	0x5e, 0xdb, 0x69, 0x69, 0x6b, 0xa8, 0x04, 0xb9, 0xd7, 0xd8, 0xd3, 0x32, 0xa8, 0x0c, 0xf9, 0x36,
	0x36, 0x5a, 0x5a, 0x96, 0xaf, 0x7a, 0x8e, 0xeb, 0x69, 0x39, 0xbe, 0xd9, 0xeb, 0x7b, 0xb2, 0x75,
	0xb7, 0x70, 0x07, 0x7b, 0x58, 0xb6, 0x6e, 0xd3, 0xb1, 0x6d, 0x6c, 0x7a, 0x5a, 0x91, 0x13, 0x4e,
	0xcf, 0xb3, 0x1c, 0xdb, 0xd5, 0x4a, 0xa8, 0x02, 0x05, 0x8f, 0x18, 0x26, 0xd6, 0xca, 0xc7, 0x05,
	0xc8, 0xf5, 0x89, 0xd5, 0xf8, 0xf7, 0x16, 0x94, 0x17, 0x73, 0xcc, 0xaf, 0x20, 0x6f, 0x06, 0xa3,
	0x64, 0x84, 0xd1, 0xd5, 0xdb, 0xab, 0xa1, 0x85, 0xef, 0xa8, 0x57, 0x17, 0x5c, 0xe8, 0xd5, 0xb2,
	0x61, 0x66, 0x45, 0x76, 0x3d, 0xba, 0x2d, 0x70, 0xb7, 0x63, 0xf2, 0xca, 0x79, 0x1c, 0x8c, 0x6e,
	0x44, 0x6f, 0xab, 0x11, 0xb1, 0xde, 0xfd, 0x1b, 0x5a, 0x76, 0xd1, 0x3e, 0xec, 0xdf, 0xe9, 0x19,
	0xc6, 0x74, 0x1a, 0x7c, 0xa0, 0xb2, 0x28, 0x70, 0x42, 0x59, 0x76, 0x6f, 0x1c, 0xb8, 0xdd, 0x2f,
	0x84, 0x94, 0x14, 0x32, 0xa6, 0x53, 0x44, 0xe1, 0xd9, 0x43, 0x6a, 0xe5, 0x4f, 0x72, 0x87, 0x0d,
	0xa1, 0x7a, 0x39, 0x1b, 0xb7, 0xd7, 0xc8, 0xfe, 0xc7, 0x94, 0x2b, 0x49, 0xf4, 0xa7, 0x0c, 0x1c,
	0xa4, 0x9e, 0x60, 0x86, 0x6c, 0xc4, 0xe6, 0xf1, 0xc4, 0x9f, 0x46, 0xe2, 0xd2, 0xf5, 0xa3, 0x1f,
	0x53, 0x5d, 0xd4, 0xfc, 0x94, 0xb4, 0xf2, 0xfb, 0xde, 0x7d, 0x4b, 0x56, 0x98, 0x90, 0x71, 0xaf,
	0x97, 0xe3, 0xeb, 0xcb, 0x20, 0x62, 0x8b, 0x96, 0x9b, 0x17, 0x65, 0xe5, 0x76, 0xdb, 0x96, 0x2c,
	0xc9, 0x13, 0x7c, 0x0b, 0xeb, 0xc6, 0x34, 0xa6, 0xee, 0xfb, 0x21, 0x35, 0xa7, 0xcc, 0x0f, 0xc5,
	0xd4, 0x50, 0x3f, 0x02, 0x39, 0xcd, 0x72, 0xa4, 0x9d, 0x21, 0x55, 0x63, 0x1a, 0xbb, 0xef, 0x87,
	0x82, 0x44, 0x06, 0x9f, 0x5a, 0xc3, 0xf7, 0x93, 0x21, 0x13, 0xa3, 0x42, 0x55, 0x7d, 0x05, 0xdc,
	0xbf, 0xa2, 0x52, 0xdb, 0x65, 0x51, 0xe4, 0x8f, 0x59, 0x3b, 0x43, 0x12, 0x39, 0xd4, 0x85, 0x1a,
	0x37, 0x86, 0xcd, 0x63, 0xea, 0xdd, 0x5c, 0x32, 0x35, 0x19, 0xbc, 0x48, 0xd7, 0xb3, 0xca, 0x99,
	0x28, 0x23, 0x55, 0x85, 0x72, 0x10, 0x35, 0x21, 0xcf, 0x07, 0x26, 0x31, 0x16, 0x3c, 0xdc, 0xb4,
	0x04, 0x1f, 0xfa, 0x01, 0x36, 0xf0, 0xf5, 0xe5, 0x24, 0x64, 0x11, 0x35, 0xa6, 0x21, 0xf3, 0x47,
	0x37, 0x62, 0x64, 0xa8, 0x1f, 0xd5, 0x84, 0x05, 0x0a, 0x6b, 0x67, 0x49, 0x5d, 0xb1, 0x29, 0x04,
	0xfd, 0x0e, 0x6a, 0x89, 0xa0, 0x38, 0x10, 0x3e, 0x75, 0x60, 0x3b, 0x4b, 0xaa, 0x4a, 0x42, 0x9c,
	0xbc, 0x03, 0x45, 0xee, 0x03, 0x16, 0xaa, 0x01, 0x43, 0x51, 0xe8, 0x05, 0x94, 0x4f, 0xfd, 0xf0,
	0x46, 0x44, 0x7c, 0x2d, 0x2d, 0xe2, 0x73, 0xa4, 0xc4, 0x19, 0x78, 0x74, 0x7f, 0x0f, 0x35, 0xc1,
	0x9b, 0xbc, 0xf1, 0x7a, 0x7a, 0x18, 0xe7, 0x48, 0x95, 0xb3, 0x25, 0xef, 0xec, 0xc2, 0xc6, 0x80,
	0x9e, 0x84, 0xfe, 0x8c, 0x51, 0xe7, 0x92, 0x77, 0xca, 0x48, 0x0c, 0x24, 0xcb, 0xd6, 0x71, 0xc7,
	0xeb, 0x77, 0x98, 0x55, 0x3c, 0xae, 0x0f, 0x04, 0xaa, 0x40, 0x74, 0xc8, 0x1b, 0xd2, 0xc0, 0x75,
	0x69, 0x2f, 0x0c, 0x62, 0xfe, 0xb1, 0x12, 0xcc, 0xc5, 0x08, 0x53, 0x21, 0xf5, 0xc1, 0xc0, 0x75,
	0x97, 0x28, 0x7a, 0x0d, 0xe0, 0xb2, 0x98, 0x9a, 0x41, 0xf0, 0x87, 0x09, 0xd3, 0x35, 0xd1, 0x36,
	0x0e, 0xd3, 0x4f, 0x5e, 0xf2, 0x2d, 0x5e, 0xbb, 0xe2, 0xb2, 0x58, 0x42, 0xcb, 0xd6, 0xb3, 0xf9,
	0x40, 0xeb, 0xf9, 0x4f, 0x06, 0x36, 0xee, 0x84, 0x1f, 0xb2, 0xa0, 0xac, 0xc2, 0x4f, 0x7e, 0xf3,
	0x56, 0x17, 0xcd, 0xfc, 0xe1, 0xb8, 0x6d, 0x2a, 0x29, 0xb2, 0x10, 0x47, 0x5f, 0x40, 0x89, 0xcf,
	0x39, 0xc6, 0x98, 0xa9, 0xd6, 0x55, 0xec, 0xfa, 0xd7, 0xc6, 0x58, 0x7c, 0xd0, 0xf5, 0x58, 0x18,
	0x4d, 0xa2, 0x58, 0x64, 0x7f, 0x99, 0x24, 0xe4, 0xae, 0xbd, 0x48, 0x1a, 0x5e, 0x14, 0x6d, 0x7f,
	0xc6, 0xd4, 0x87, 0x83, 0x58, 0xa3, 0xc7, 0x50, 0xe1, 0x63, 0x25, 0x15, 0x1b, 0xf2, 0x8b, 0xa1,
	0xcc, 0x01, 0xb1, 0x89, 0x20, 0xdf, 0x0b, 0x42, 0xa9, 0x72, 0x9d, 0x88, 0xf5, 0xee, 0xbf, 0xb2,
	0xb0, 0x9d, 0x96, 0x18, 0xe8, 0x02, 0x34, 0x33, 0x98, 0xcd, 0x82, 0x39, 0xed, 0x5a, 0x5d, 0x2c,
	0xd3, 0x2b, 0xf3, 0x50, 0x25, 0x4a, 0xd3, 0xd2, 0xbc, 0xab, 0x22, 0x6a, 0xaf, 0x91, 0xba, 0x04,
	0x39, 0x26, 0xb2, 0x6e, 0x27, 0x79, 0x89, 0xac, 0xfa, 0xfe, 0x92, 0x24, 0x9f, 0xb7, 0x7b, 0x3e,
	0x8f, 0x92, 0x98, 0x85, 0xc2, 0xe6, 0xfb, 0xf3, 0xf6, 0x62, 0xbf, 0x71, 0x0a, 0x9b, 0xf7, 0xce,
	0x5a, 0xe9, 0xab, 0x12, 0x3c, 0xeb, 0xf1, 0xbe, 0xfa, 0x04, 0x74, 0xa3, 0xd7, 0xeb, 0x58, 0xa6,
	0xc1, 0x9b, 0x1b, 0x75, 0x4c, 0x0f, 0x7b, 0xd4, 0xf5, 0x08, 0x36, 0xba, 0xf2, 0xcf, 0x00, 0x0f,
	0x0f, 0x3c, 0xda, 0xf6, 0xba, 0x1d, 0x2d, 0x7b, 0xbc, 0x93, 0xee, 0x9e, 0xdd, 0xbf, 0xe4, 0x00,
	0xdd, 0x0f, 0xb0, 0xd4, 0x37, 0x49, 0xfd, 0x1f, 0x05, 0x7d, 0x0f, 0x25, 0x95, 0xd0, 0xea, 0x6e,
	0x0f, 0x95, 0x9b, 0x84, 0x75, 0x35, 0x62, 0xf8, 0xe7, 0x5b, 0x6e, 0x11, 0x31, 0x3b, 0x50, 0x6c,
	0x05, 0x33, 0x7f, 0x32, 0x57, 0x5f, 0x6b, 0x8a, 0x12, 0x6f, 0xee, 0xc7, 0x17, 0xa2, 0xc2, 0x56,
	0x88, 0x58, 0xcb, 0xe2, 0x31, 0xbc, 0x0a, 0x65, 0xbd, 0x2c, 0x13, 0x45, 0xa1, 0x5d, 0x28, 0xb7,
	0xe3, 0xf8, 0xd2, 0x99, 0x4f, 0x6f, 0x44, 0x09, 0x2c, 0x93, 0x05, 0x8d, 0x5c, 0x28, 0xbb, 0xfe,
	0x8c, 0xb9, 0x93, 0x98, 0xa9, 0x1a, 0xf7, 0xc3, 0xe7, 0x66, 0x5d, 0x33, 0x11, 0x54, 0xb9, 0xbf,
	0x50, 0xd4, 0xf8, 0x09, 0xea, 0xb7, 0xf7, 0xd0, 0x97, 0xf0, 0x48, 0xbd, 0x98, 0x6b, 0x74, 0xb1,
	0x6b, 0x79, 0x78, 0x31, 0x0e, 0x01, 0x14, 0x5d, 0x8f, 0x58, 0x26, 0x1f, 0x68, 0x4a, 0x90, 0xeb,
	0x18, 0x03, 0x39, 0xcf, 0xd8, 0x8e, 0x8d, 0xb5, 0x5c, 0xe3, 0x12, 0x9e, 0x7f, 0x5e, 0x2f, 0x44,
	0xbf, 0x86, 0x6f, 0xd4, 0x19, 0x86, 0x69, 0x62, 0xd7, 0xa5, 0xa6, 0x63, 0x7b, 0xc4, 0xe9, 0x50,
	0xa3, 0xd3, 0x71, 0xde, 0x52, 0x93, 0xe0, 0x16, 0xb6, 0x3d, 0xcb, 0xe8, 0x2c, 0x87, 0xc1, 0x0a,
	0x14, 0x4e, 0x8c, 0x8e, 0x8b, 0xe5, 0x2c, 0xe5, 0x91, 0x3e, 0xd6, 0xb2, 0x0d, 0x17, 0x1e, 0xa5,
	0x16, 0x37, 0x74, 0x00, 0x4f, 0x16, 0x23, 0xe1, 0x09, 0x31, 0xba, 0x98, 0xaa, 0x39, 0x6a, 0xa1,
	0xaf, 0x0c, 0xf9, 0x16, 0xb6, 0xcf, 0xb4, 0x0c, 0xaa, 0x03, 0xf0, 0x9b, 0x3a, 0xc4, 0x7a, 0x6d,
	0xd9, 0x5a, 0xf6, 0x78, 0x0f, 0x1e, 0x3f, 0x30, 0x72, 0x1c, 0x57, 0xa0, 0xa4, 0xca, 0x0a, 0x5f,
	0xaa, 0xa8, 0x38, 0x2e, 0x42, 0x9e, 0x97, 0xe8, 0xc6, 0x73, 0x80, 0xe5, 0xac, 0x85, 0x36, 0xa0,
	0xaa, 0xcc, 0x30, 0x9d, 0x16, 0x16, 0xf3, 0x60, 0xd6, 0x79, 0xa3, 0xfd, 0x92, 0x79, 0xb1, 0x0d,
	0xe5, 0xc5, 0x5f, 0x20, 0x65, 0xc8, 0xbb, 0x9e, 0x41, 0xb4, 0xb5, 0x17, 0x3b, 0x5c, 0xb7, 0xec,
	0x4f, 0x55, 0x28, 0x19, 0x1d, 0x82, 0x8d, 0xd6, 0x99, 0xb6, 0xf6, 0x02, 0x41, 0x41, 0x36, 0xec,
	0x0a, 0x14, 0xcc, 0x0e, 0xe6, 0xbc, 0xef, 0x8a, 0x22, 0x48, 0xbf, 0xfb, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa3, 0x12, 0xcb, 0x85, 0x73, 0x14, 0x00, 0x00,
}
