// Code generated by protoc-gen-go. DO NOT EDIT.
// source: web.proto

package web

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request_Method int32

const (
	Request_UNUSED_METHOD Request_Method = 0
	Request_GET           Request_Method = 1
	Request_HEAD          Request_Method = 2
	Request_POST          Request_Method = 3
	Request_PUT           Request_Method = 4
	Request_DELETE        Request_Method = 5
	Request_CONNECT       Request_Method = 6
	Request_OPTIONS       Request_Method = 7
	Request_TRACE         Request_Method = 8
)

var Request_Method_name = map[int32]string{
	0: "UNUSED_METHOD",
	1: "GET",
	2: "HEAD",
	3: "POST",
	4: "PUT",
	5: "DELETE",
	6: "CONNECT",
	7: "OPTIONS",
	8: "TRACE",
}

var Request_Method_value = map[string]int32{
	"UNUSED_METHOD": 0,
	"GET":           1,
	"HEAD":          2,
	"POST":          3,
	"PUT":           4,
	"DELETE":        5,
	"CONNECT":       6,
	"OPTIONS":       7,
	"TRACE":         8,
}

func (x Request_Method) String() string {
	return proto.EnumName(Request_Method_name, int32(x))
}

func (Request_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{1, 0}
}

type Request_Headers_Transfer_Encodings_Value int32

const (
	// only trailers is supported in HTTP/2
	Request_Headers_UNUSED_TRANSFER_ENCODINGS_VALUE Request_Headers_Transfer_Encodings_Value = 0
	Request_Headers_TRAILERS                        Request_Headers_Transfer_Encodings_Value = 1
)

var Request_Headers_Transfer_Encodings_Value_name = map[int32]string{
	0: "UNUSED_TRANSFER_ENCODINGS_VALUE",
	1: "TRAILERS",
}

var Request_Headers_Transfer_Encodings_Value_value = map[string]int32{
	"UNUSED_TRANSFER_ENCODINGS_VALUE": 0,
	"TRAILERS":                        1,
}

func (x Request_Headers_Transfer_Encodings_Value) String() string {
	return proto.EnumName(Request_Headers_Transfer_Encodings_Value_name, int32(x))
}

func (Request_Headers_Transfer_Encodings_Value) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{1, 0, 0}
}

type Request_Headers_X_Requested_With_Value int32

const (
	Request_Headers_UNUSED_X_REQUESTED_WITH_VALUE Request_Headers_X_Requested_With_Value = 0
	Request_Headers_XMLHTTPREQUEST                Request_Headers_X_Requested_With_Value = 1
)

var Request_Headers_X_Requested_With_Value_name = map[int32]string{
	0: "UNUSED_X_REQUESTED_WITH_VALUE",
	1: "XMLHTTPREQUEST",
}

var Request_Headers_X_Requested_With_Value_value = map[string]int32{
	"UNUSED_X_REQUESTED_WITH_VALUE": 0,
	"XMLHTTPREQUEST":                1,
}

func (x Request_Headers_X_Requested_With_Value) String() string {
	return proto.EnumName(Request_Headers_X_Requested_With_Value_name, int32(x))
}

func (Request_Headers_X_Requested_With_Value) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{1, 0, 1}
}

type Request_Headers_DNT_Value int32

const (
	Request_Headers_UNUSED_DNT_VALUE Request_Headers_DNT_Value = 0
	Request_Headers_DISABLED         Request_Headers_DNT_Value = 1
	Request_Headers_ENABLED          Request_Headers_DNT_Value = 2
)

var Request_Headers_DNT_Value_name = map[int32]string{
	0: "UNUSED_DNT_VALUE",
	1: "DISABLED",
	2: "ENABLED",
}

var Request_Headers_DNT_Value_value = map[string]int32{
	"UNUSED_DNT_VALUE": 0,
	"DISABLED":         1,
	"ENABLED":          2,
}

func (x Request_Headers_DNT_Value) String() string {
	return proto.EnumName(Request_Headers_DNT_Value_name, int32(x))
}

func (Request_Headers_DNT_Value) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{1, 0, 2}
}

type Response_Codes int32

const (
	Response_UNUSED_CODE Response_Codes = 0
	Response_OK          Response_Codes = 200
)

var Response_Codes_name = map[int32]string{
	0:   "UNUSED_CODE",
	200: "OK",
}

var Response_Codes_value = map[string]int32{
	"UNUSED_CODE": 0,
	"OK":          200,
}

func (x Response_Codes) String() string {
	return proto.EnumName(Response_Codes_name, int32(x))
}

func (Response_Codes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{2, 0}
}

type Response_Headers_Access_Control_Allow_Credentials_Value int32

const (
	Response_Headers_UNUSED_ACCESS_CONTROL_ALLOW_CREDENTIALS_VALUE Response_Headers_Access_Control_Allow_Credentials_Value = 0
	Response_Headers_FALSE                                         Response_Headers_Access_Control_Allow_Credentials_Value = 1
	Response_Headers_TRUE                                          Response_Headers_Access_Control_Allow_Credentials_Value = 2
)

var Response_Headers_Access_Control_Allow_Credentials_Value_name = map[int32]string{
	0: "UNUSED_ACCESS_CONTROL_ALLOW_CREDENTIALS_VALUE",
	1: "FALSE",
	2: "TRUE",
}

var Response_Headers_Access_Control_Allow_Credentials_Value_value = map[string]int32{
	"UNUSED_ACCESS_CONTROL_ALLOW_CREDENTIALS_VALUE": 0,
	"FALSE": 1,
	"TRUE":  2,
}

func (x Response_Headers_Access_Control_Allow_Credentials_Value) String() string {
	return proto.EnumName(Response_Headers_Access_Control_Allow_Credentials_Value_name, int32(x))
}

func (Response_Headers_Access_Control_Allow_Credentials_Value) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{2, 0, 0}
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{0}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Request struct {
	Method Request_Method `protobuf:"varint,1,opt,name=method,proto3,enum=web.Request_Method" json:"method,omitempty"`
	// Unset URI implies server-wide "*" request, i.e. for OPTIONS
	// TODO: separate absolute vs. relative?
	Uri                  string           `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Query                []*KeyValue      `protobuf:"bytes,3,rep,name=query,proto3" json:"query,omitempty"`
	Headers              *Request_Headers `protobuf:"bytes,4,opt,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMethod() Request_Method {
	if m != nil {
		return m.Method
	}
	return Request_UNUSED_METHOD
}

func (m *Request) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Request) GetQuery() []*KeyValue {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *Request) GetHeaders() *Request_Headers {
	if m != nil {
		return m.Headers
	}
	return nil
}

type Request_Headers struct {
	Accept                         string               `protobuf:"bytes,1,opt,name=Accept,proto3" json:"Accept,omitempty"`
	Accept_Charset                 string               `protobuf:"bytes,2,opt,name=Accept_Charset,json=AcceptCharset,proto3" json:"Accept_Charset,omitempty"`
	Accept_Datetime                string               `protobuf:"bytes,3,opt,name=Accept_Datetime,json=AcceptDatetime,proto3" json:"Accept_Datetime,omitempty"`
	Accept_Encoding                string               `protobuf:"bytes,4,opt,name=Accept_Encoding,json=AcceptEncoding,proto3" json:"Accept_Encoding,omitempty"`
	Accept_Language                string               `protobuf:"bytes,5,opt,name=Accept_Language,json=AcceptLanguage,proto3" json:"Accept_Language,omitempty"`
	Access_Control_Request_Method  Request_Method       `protobuf:"varint,6,opt,name=Access_Control_Request_Method,json=AccessControlRequestMethod,proto3,enum=web.Request_Method" json:"Access_Control_Request_Method,omitempty"`
	Access_Control_Request_Headers *Request_Headers     `protobuf:"bytes,7,opt,name=Access_Control_Request_Headers,json=AccessControlRequestHeaders,proto3" json:"Access_Control_Request_Headers,omitempty"`
	Authorization                  string               `protobuf:"bytes,8,opt,name=Authorization,proto3" json:"Authorization,omitempty"`
	Expect                         string               `protobuf:"bytes,9,opt,name=Expect,proto3" json:"Expect,omitempty"`
	Forwarded                      []*KeyValue          `protobuf:"bytes,10,rep,name=Forwarded,proto3" json:"Forwarded,omitempty"`
	From                           string               `protobuf:"bytes,11,opt,name=From,proto3" json:"From,omitempty"`
	Host                           string               `protobuf:"bytes,12,opt,name=Host,proto3" json:"Host,omitempty"`
	HTTP2_Settings                 string               `protobuf:"bytes,13,opt,name=HTTP2_Settings,json=HTTP2Settings,proto3" json:"HTTP2_Settings,omitempty"`
	If_Match                       string               `protobuf:"bytes,14,opt,name=If_Match,json=IfMatch,proto3" json:"If_Match,omitempty"`
	If_Modified_Since              *timestamp.Timestamp `protobuf:"bytes,15,opt,name=If_Modified_Since,json=IfModifiedSince,proto3" json:"If_Modified_Since,omitempty"`
	If_None_Match                  string               `protobuf:"bytes,16,opt,name=If_None_Match,json=IfNoneMatch,proto3" json:"If_None_Match,omitempty"`
	If_Range                       string               `protobuf:"bytes,17,opt,name=If_Range,json=IfRange,proto3" json:"If_Range,omitempty"`
	If_Unmodified_Since            *timestamp.Timestamp `protobuf:"bytes,18,opt,name=If_Unmodified_Since,json=IfUnmodifiedSince,proto3" json:"If_Unmodified_Since,omitempty"`
	Max_Forwards                   uint64               `protobuf:"varint,19,opt,name=Max_Forwards,json=MaxForwards,proto3" json:"Max_Forwards,omitempty"`
	Origin                         string               `protobuf:"bytes,20,opt,name=Origin,proto3" json:"Origin,omitempty"`
	Pragma                         string               `protobuf:"bytes,21,opt,name=Pragma,proto3" json:"Pragma,omitempty"`
	Proxy_Authorization            string               `protobuf:"bytes,22,opt,name=Proxy_Authorization,json=ProxyAuthorization,proto3" json:"Proxy_Authorization,omitempty"`
	// Types that are valid to be assigned to Range:
	//	*Request_Headers_Bytes
	Range                isRequest_Headers_Range                    `protobuf_oneof:"Range"`
	Referer              string                                     `protobuf:"bytes,24,opt,name=Referer,proto3" json:"Referer,omitempty"`
	TE                   []Request_Headers_Transfer_Encodings_Value `protobuf:"varint,25,rep,packed,name=TE,proto3,enum=web.Request_Headers_Transfer_Encodings_Value" json:"TE,omitempty"`
	User_Agent           string                                     `protobuf:"bytes,26,opt,name=User_Agent,json=UserAgent,proto3" json:"User_Agent,omitempty"`
	Via                  []string                                   `protobuf:"bytes,27,rep,name=Via,proto3" json:"Via,omitempty"`
	Warning              string                                     `protobuf:"bytes,28,opt,name=Warning,proto3" json:"Warning,omitempty"`
	X_Requested_With     Request_Headers_X_Requested_With_Value     `protobuf:"varint,29,opt,name=X_Requested_With,json=XRequestedWith,proto3,enum=web.Request_Headers_X_Requested_With_Value" json:"X_Requested_With,omitempty"`
	DNT                  Request_Headers_DNT_Value                  `protobuf:"varint,30,opt,name=DNT,proto3,enum=web.Request_Headers_DNT_Value" json:"DNT,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *Request_Headers) Reset()         { *m = Request_Headers{} }
func (m *Request_Headers) String() string { return proto.CompactTextString(m) }
func (*Request_Headers) ProtoMessage()    {}
func (*Request_Headers) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{1, 0}
}

func (m *Request_Headers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Headers.Unmarshal(m, b)
}
func (m *Request_Headers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Headers.Marshal(b, m, deterministic)
}
func (m *Request_Headers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Headers.Merge(m, src)
}
func (m *Request_Headers) XXX_Size() int {
	return xxx_messageInfo_Request_Headers.Size(m)
}
func (m *Request_Headers) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Headers.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Headers proto.InternalMessageInfo

func (m *Request_Headers) GetAccept() string {
	if m != nil {
		return m.Accept
	}
	return ""
}

func (m *Request_Headers) GetAccept_Charset() string {
	if m != nil {
		return m.Accept_Charset
	}
	return ""
}

func (m *Request_Headers) GetAccept_Datetime() string {
	if m != nil {
		return m.Accept_Datetime
	}
	return ""
}

func (m *Request_Headers) GetAccept_Encoding() string {
	if m != nil {
		return m.Accept_Encoding
	}
	return ""
}

func (m *Request_Headers) GetAccept_Language() string {
	if m != nil {
		return m.Accept_Language
	}
	return ""
}

func (m *Request_Headers) GetAccess_Control_Request_Method() Request_Method {
	if m != nil {
		return m.Access_Control_Request_Method
	}
	return Request_UNUSED_METHOD
}

func (m *Request_Headers) GetAccess_Control_Request_Headers() *Request_Headers {
	if m != nil {
		return m.Access_Control_Request_Headers
	}
	return nil
}

func (m *Request_Headers) GetAuthorization() string {
	if m != nil {
		return m.Authorization
	}
	return ""
}

func (m *Request_Headers) GetExpect() string {
	if m != nil {
		return m.Expect
	}
	return ""
}

func (m *Request_Headers) GetForwarded() []*KeyValue {
	if m != nil {
		return m.Forwarded
	}
	return nil
}

func (m *Request_Headers) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Request_Headers) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Request_Headers) GetHTTP2_Settings() string {
	if m != nil {
		return m.HTTP2_Settings
	}
	return ""
}

func (m *Request_Headers) GetIf_Match() string {
	if m != nil {
		return m.If_Match
	}
	return ""
}

func (m *Request_Headers) GetIf_Modified_Since() *timestamp.Timestamp {
	if m != nil {
		return m.If_Modified_Since
	}
	return nil
}

func (m *Request_Headers) GetIf_None_Match() string {
	if m != nil {
		return m.If_None_Match
	}
	return ""
}

func (m *Request_Headers) GetIf_Range() string {
	if m != nil {
		return m.If_Range
	}
	return ""
}

func (m *Request_Headers) GetIf_Unmodified_Since() *timestamp.Timestamp {
	if m != nil {
		return m.If_Unmodified_Since
	}
	return nil
}

func (m *Request_Headers) GetMax_Forwards() uint64 {
	if m != nil {
		return m.Max_Forwards
	}
	return 0
}

func (m *Request_Headers) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Request_Headers) GetPragma() string {
	if m != nil {
		return m.Pragma
	}
	return ""
}

func (m *Request_Headers) GetProxy_Authorization() string {
	if m != nil {
		return m.Proxy_Authorization
	}
	return ""
}

type isRequest_Headers_Range interface {
	isRequest_Headers_Range()
}

type Request_Headers_Bytes struct {
	Bytes *Request_Headers_ByteRange `protobuf:"bytes,23,opt,name=bytes,proto3,oneof"`
}

func (*Request_Headers_Bytes) isRequest_Headers_Range() {}

func (m *Request_Headers) GetRange() isRequest_Headers_Range {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *Request_Headers) GetBytes() *Request_Headers_ByteRange {
	if x, ok := m.GetRange().(*Request_Headers_Bytes); ok {
		return x.Bytes
	}
	return nil
}

func (m *Request_Headers) GetReferer() string {
	if m != nil {
		return m.Referer
	}
	return ""
}

func (m *Request_Headers) GetTE() []Request_Headers_Transfer_Encodings_Value {
	if m != nil {
		return m.TE
	}
	return nil
}

func (m *Request_Headers) GetUser_Agent() string {
	if m != nil {
		return m.User_Agent
	}
	return ""
}

func (m *Request_Headers) GetVia() []string {
	if m != nil {
		return m.Via
	}
	return nil
}

func (m *Request_Headers) GetWarning() string {
	if m != nil {
		return m.Warning
	}
	return ""
}

func (m *Request_Headers) GetX_Requested_With() Request_Headers_X_Requested_With_Value {
	if m != nil {
		return m.X_Requested_With
	}
	return Request_Headers_UNUSED_X_REQUESTED_WITH_VALUE
}

func (m *Request_Headers) GetDNT() Request_Headers_DNT_Value {
	if m != nil {
		return m.DNT
	}
	return Request_Headers_UNUSED_DNT_VALUE
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Request_Headers) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Request_Headers_Bytes)(nil),
	}
}

type Request_Headers_ByteRange struct {
	Start                uint64   `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  uint64   `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Headers_ByteRange) Reset()         { *m = Request_Headers_ByteRange{} }
func (m *Request_Headers_ByteRange) String() string { return proto.CompactTextString(m) }
func (*Request_Headers_ByteRange) ProtoMessage()    {}
func (*Request_Headers_ByteRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{1, 0, 0}
}

func (m *Request_Headers_ByteRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Headers_ByteRange.Unmarshal(m, b)
}
func (m *Request_Headers_ByteRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Headers_ByteRange.Marshal(b, m, deterministic)
}
func (m *Request_Headers_ByteRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Headers_ByteRange.Merge(m, src)
}
func (m *Request_Headers_ByteRange) XXX_Size() int {
	return xxx_messageInfo_Request_Headers_ByteRange.Size(m)
}
func (m *Request_Headers_ByteRange) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Headers_ByteRange.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Headers_ByteRange proto.InternalMessageInfo

func (m *Request_Headers_ByteRange) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Request_Headers_ByteRange) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

type Response struct {
	Code                 Response_Codes `protobuf:"varint,1,opt,name=Code,proto3,enum=web.Response_Codes" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() Response_Codes {
	if m != nil {
		return m.Code
	}
	return Response_UNUSED_CODE
}

type Response_Headers struct {
	Access_Control_Allow_Origins     string                                                  `protobuf:"bytes,1,opt,name=Access_Control_Allow_Origins,json=AccessControlAllowOrigins,proto3" json:"Access_Control_Allow_Origins,omitempty"`
	Access_Control_Allow_Credentials Response_Headers_Access_Control_Allow_Credentials_Value `protobuf:"varint,2,opt,name=Access_Control_Allow_Credentials,json=AccessControlAllowCredentials,proto3,enum=web.Response_Headers_Access_Control_Allow_Credentials_Value" json:"Access_Control_Allow_Credentials,omitempty"`
	Access_Control_Expose_Headers    []string                                                `protobuf:"bytes,3,rep,name=Access_Control_Expose_Headers,json=AccessControlExposeHeaders,proto3" json:"Access_Control_Expose_Headers,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}                                                `json:"-"`
	XXX_unrecognized                 []byte                                                  `json:"-"`
	XXX_sizecache                    int32                                                   `json:"-"`
}

func (m *Response_Headers) Reset()         { *m = Response_Headers{} }
func (m *Response_Headers) String() string { return proto.CompactTextString(m) }
func (*Response_Headers) ProtoMessage()    {}
func (*Response_Headers) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{2, 0}
}

func (m *Response_Headers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Headers.Unmarshal(m, b)
}
func (m *Response_Headers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Headers.Marshal(b, m, deterministic)
}
func (m *Response_Headers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Headers.Merge(m, src)
}
func (m *Response_Headers) XXX_Size() int {
	return xxx_messageInfo_Response_Headers.Size(m)
}
func (m *Response_Headers) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Headers.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Headers proto.InternalMessageInfo

func (m *Response_Headers) GetAccess_Control_Allow_Origins() string {
	if m != nil {
		return m.Access_Control_Allow_Origins
	}
	return ""
}

func (m *Response_Headers) GetAccess_Control_Allow_Credentials() Response_Headers_Access_Control_Allow_Credentials_Value {
	if m != nil {
		return m.Access_Control_Allow_Credentials
	}
	return Response_Headers_UNUSED_ACCESS_CONTROL_ALLOW_CREDENTIALS_VALUE
}

func (m *Response_Headers) GetAccess_Control_Expose_Headers() []string {
	if m != nil {
		return m.Access_Control_Expose_Headers
	}
	return nil
}

func init() {
	proto.RegisterEnum("web.Request_Method", Request_Method_name, Request_Method_value)
	proto.RegisterEnum("web.Request_Headers_Transfer_Encodings_Value", Request_Headers_Transfer_Encodings_Value_name, Request_Headers_Transfer_Encodings_Value_value)
	proto.RegisterEnum("web.Request_Headers_X_Requested_With_Value", Request_Headers_X_Requested_With_Value_name, Request_Headers_X_Requested_With_Value_value)
	proto.RegisterEnum("web.Request_Headers_DNT_Value", Request_Headers_DNT_Value_name, Request_Headers_DNT_Value_value)
	proto.RegisterEnum("web.Response_Codes", Response_Codes_name, Response_Codes_value)
	proto.RegisterEnum("web.Response_Headers_Access_Control_Allow_Credentials_Value", Response_Headers_Access_Control_Allow_Credentials_Value_name, Response_Headers_Access_Control_Allow_Credentials_Value_value)
	proto.RegisterType((*KeyValue)(nil), "web.KeyValue")
	proto.RegisterType((*Request)(nil), "web.Request")
	proto.RegisterType((*Request_Headers)(nil), "web.Request.Headers")
	proto.RegisterType((*Request_Headers_ByteRange)(nil), "web.Request.Headers.ByteRange")
	proto.RegisterType((*Response)(nil), "web.Response")
	proto.RegisterType((*Response_Headers)(nil), "web.Response.Headers")
}

func init() { proto.RegisterFile("web.proto", fileDescriptor_461bb3ac99194e85) }

var fileDescriptor_461bb3ac99194e85 = []byte{
	// 1208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xed, 0x72, 0xda, 0x46,
	0x17, 0x0e, 0xdf, 0x70, 0xb0, 0xb1, 0xbc, 0xf6, 0x9b, 0x77, 0x43, 0xe2, 0x04, 0x93, 0xf7, 0xc3,
	0x33, 0x99, 0xe0, 0x96, 0xcc, 0xf4, 0x57, 0x3a, 0x1d, 0x19, 0xad, 0x83, 0x1a, 0x90, 0x5c, 0x49,
	0xd8, 0x6e, 0xff, 0x68, 0x04, 0x2c, 0xa0, 0x89, 0x91, 0x88, 0x24, 0x62, 0xbb, 0xff, 0x3b, 0xbd,
	0x90, 0x5e, 0x44, 0x6f, 0xa1, 0x97, 0xd1, 0x4b, 0xe9, 0xec, 0x87, 0xb0, 0x49, 0x48, 0xd3, 0x7f,
	0x7b, 0x9e, 0xf3, 0x9c, 0xa3, 0x67, 0xcf, 0x9e, 0xb3, 0x2b, 0xa8, 0x5c, 0xd3, 0x61, 0x6b, 0x11,
	0x85, 0x49, 0x88, 0x72, 0xd7, 0x74, 0x58, 0x7f, 0x36, 0x0d, 0xc3, 0xe9, 0x15, 0x3d, 0xe6, 0xd0,
	0x70, 0x39, 0x39, 0x4e, 0xfc, 0x39, 0x8d, 0x13, 0x6f, 0xbe, 0x10, 0xac, 0x66, 0x1b, 0xca, 0x6f,
	0xe9, 0xed, 0xb9, 0x77, 0xb5, 0xa4, 0x48, 0x81, 0xdc, 0x3b, 0x7a, 0x8b, 0x33, 0x8d, 0xcc, 0x51,
	0xc5, 0x62, 0x4b, 0xb4, 0x0f, 0x85, 0x0f, 0xcc, 0x85, 0xb3, 0x1c, 0x13, 0x46, 0xf3, 0xf7, 0x1a,
	0x94, 0x2c, 0xfa, 0x7e, 0x49, 0xe3, 0x04, 0xbd, 0x80, 0xe2, 0x9c, 0x26, 0xb3, 0x70, 0xcc, 0xc3,
	0x6a, 0xed, 0xbd, 0x16, 0x53, 0x20, 0xbd, 0xad, 0x3e, 0x77, 0x59, 0x92, 0xc2, 0x3e, 0xb0, 0x8c,
	0x7c, 0x99, 0x8c, 0x2d, 0xd1, 0x73, 0x28, 0xbc, 0x5f, 0xd2, 0xe8, 0x16, 0xe7, 0x1a, 0xb9, 0xa3,
	0x6a, 0x7b, 0x9b, 0x47, 0xa7, 0x82, 0x2c, 0xe1, 0x43, 0x2d, 0x28, 0xcd, 0xa8, 0x37, 0xa6, 0x51,
	0x8c, 0xf3, 0x8d, 0xcc, 0x51, 0xb5, 0xbd, 0xbf, 0xf6, 0x91, 0xae, 0xf0, 0x59, 0x29, 0xa9, 0xfe,
	0xdb, 0x16, 0x94, 0x24, 0x88, 0x1e, 0x42, 0x51, 0x1d, 0x8d, 0xe8, 0x22, 0x91, 0xdb, 0x92, 0x16,
	0xfa, 0x2f, 0xd4, 0xc4, 0xca, 0xed, 0xcc, 0xbc, 0x28, 0xa6, 0x89, 0x54, 0xb5, 0x2d, 0x50, 0x09,
	0xa2, 0xff, 0xc3, 0x8e, 0xa4, 0x69, 0x5e, 0x42, 0x59, 0xf1, 0x70, 0x8e, 0xf3, 0x64, 0x74, 0x8a,
	0xde, 0x23, 0x92, 0x60, 0x14, 0x8e, 0xfd, 0x60, 0xca, 0xb5, 0xae, 0x88, 0x29, 0x7a, 0x8f, 0xd8,
	0xf3, 0x82, 0xe9, 0xd2, 0x9b, 0x52, 0x5c, 0xb8, 0x4f, 0x4c, 0x51, 0x74, 0x0e, 0x07, 0x0c, 0x89,
	0x63, 0xb7, 0x13, 0x06, 0x49, 0x14, 0x5e, 0xb9, 0x72, 0xc3, 0xae, 0xa8, 0x2a, 0x2e, 0x7e, 0xbe,
	0xe0, 0x75, 0x11, 0x29, 0x03, 0xa5, 0x53, 0xf8, 0xd0, 0x8f, 0xf0, 0xf4, 0x33, 0x79, 0x65, 0xcd,
	0x70, 0xe9, 0x6f, 0x8a, 0xfc, 0x78, 0x53, 0xe6, 0xb4, 0xd8, 0xff, 0x81, 0x6d, 0x75, 0x99, 0xcc,
	0xc2, 0xc8, 0xff, 0xd9, 0x4b, 0xfc, 0x30, 0xc0, 0x65, 0x59, 0xd3, 0xfb, 0x20, 0x3b, 0x12, 0x72,
	0xb3, 0xa0, 0xa3, 0x04, 0x57, 0xc4, 0x91, 0x08, 0x0b, 0xbd, 0x80, 0xca, 0x69, 0x18, 0x5d, 0x7b,
	0xd1, 0x98, 0x8e, 0x31, 0x6c, 0xea, 0x87, 0x3b, 0x3f, 0x42, 0x90, 0x3f, 0x8d, 0xc2, 0x39, 0xae,
	0xf2, 0x14, 0x7c, 0xcd, 0xb0, 0x6e, 0x18, 0x27, 0x78, 0x4b, 0x60, 0x6c, 0xcd, 0xce, 0xb9, 0xeb,
	0x38, 0x67, 0x6d, 0xd7, 0xa6, 0x49, 0xe2, 0x07, 0xd3, 0x18, 0x6f, 0x0b, 0x4d, 0x1c, 0x4d, 0x41,
	0xf4, 0x08, 0xca, 0xfa, 0xc4, 0xed, 0x7b, 0xc9, 0x68, 0x86, 0x6b, 0x9c, 0x50, 0xd2, 0x27, 0xdc,
	0x44, 0xa7, 0xb0, 0xcb, 0x5c, 0xe1, 0xd8, 0x9f, 0xf8, 0x74, 0xec, 0xda, 0x7e, 0x30, 0xa2, 0x78,
	0x87, 0x97, 0xa8, 0xde, 0x12, 0xe3, 0xd5, 0x4a, 0xc7, 0xab, 0xe5, 0xa4, 0xe3, 0x65, 0xed, 0xe8,
	0x93, 0x34, 0x86, 0x87, 0xa0, 0x26, 0x6c, 0xeb, 0x13, 0xd7, 0x08, 0x03, 0x2a, 0xbf, 0xa3, 0xf0,
	0xef, 0x54, 0xf5, 0x09, 0xc3, 0xc4, 0xb7, 0x84, 0x0c, 0xcb, 0x0b, 0xa6, 0x14, 0xef, 0xa6, 0x32,
	0xb8, 0x89, 0xbe, 0x87, 0x3d, 0x7d, 0xe2, 0x0e, 0x82, 0xf9, 0xba, 0x10, 0xf4, 0x45, 0x21, 0xbb,
	0xfa, 0xe4, 0x2e, 0x4a, 0x48, 0x39, 0x84, 0xad, 0xbe, 0x77, 0xe3, 0xca, 0x6a, 0xc6, 0x78, 0xaf,
	0x91, 0x39, 0xca, 0x5b, 0xd5, 0xbe, 0x77, 0x93, 0x42, 0xec, 0x90, 0xcc, 0xc8, 0x9f, 0xfa, 0x01,
	0xde, 0x17, 0x87, 0x24, 0x2c, 0x86, 0x9f, 0x45, 0xde, 0x74, 0xee, 0xe1, 0x7f, 0x09, 0x5c, 0x58,
	0xe8, 0x18, 0xf6, 0xce, 0xa2, 0xf0, 0xe6, 0xd6, 0x5d, 0x6f, 0x80, 0x87, 0x9c, 0x84, 0xb8, 0x6b,
	0xbd, 0x0b, 0xbe, 0x81, 0xc2, 0xf0, 0x36, 0xa1, 0x31, 0xfe, 0x37, 0xdf, 0xc1, 0xd3, 0x4d, 0xdd,
	0xd6, 0x3a, 0xb9, 0x4d, 0x28, 0xdf, 0x7e, 0xf7, 0x81, 0x25, 0xe8, 0x08, 0xb3, 0xbb, 0x67, 0x42,
	0x23, 0x1a, 0x61, 0x2c, 0x2a, 0x24, 0x4d, 0xf4, 0x2d, 0x64, 0x1d, 0x82, 0x1f, 0x35, 0x72, 0x47,
	0xb5, 0xf6, 0xcb, 0x8d, 0xe9, 0x9c, 0xc8, 0x0b, 0xe2, 0x09, 0x8d, 0x56, 0x33, 0x1a, 0xbb, 0xa2,
	0xb1, 0xb2, 0x0e, 0x41, 0x07, 0x00, 0x83, 0x98, 0x46, 0xae, 0x3a, 0xa5, 0x41, 0x82, 0xeb, 0x3c,
	0x77, 0x85, 0x21, 0x1c, 0x60, 0x77, 0xd7, 0xb9, 0xef, 0xe1, 0xc7, 0x8d, 0x1c, 0xbb, 0xbb, 0xce,
	0x7d, 0x8f, 0x29, 0xb9, 0xf0, 0xa2, 0x80, 0x8d, 0xfa, 0x13, 0xa1, 0x44, 0x9a, 0x68, 0x00, 0xca,
	0x65, 0x3a, 0x55, 0x74, 0xec, 0x5e, 0xf8, 0xc9, 0x0c, 0x1f, 0xf0, 0x69, 0x7d, 0xb1, 0x51, 0xd7,
	0xc7, 0x64, 0xa9, 0xaa, 0x76, 0xb9, 0x82, 0x19, 0x8a, 0xbe, 0x82, 0x9c, 0x66, 0x38, 0xf8, 0x29,
	0xcf, 0xb4, 0xb9, 0x60, 0x9a, 0xe1, 0xc8, 0x60, 0x46, 0xad, 0xbf, 0x82, 0xca, 0xaa, 0x84, 0xec,
	0x32, 0x8f, 0x13, 0x2f, 0x12, 0x37, 0x61, 0xde, 0x12, 0x06, 0xdb, 0x17, 0x0d, 0xc6, 0xfc, 0xf6,
	0xcb, 0x5b, 0x6c, 0xd9, 0xec, 0x03, 0xfe, 0x5c, 0xa1, 0xd0, 0x73, 0x78, 0x36, 0x30, 0x06, 0x36,
	0xd1, 0x5c, 0xc7, 0x52, 0x0d, 0xfb, 0x94, 0x58, 0x2e, 0x31, 0x3a, 0xa6, 0xa6, 0x1b, 0x6f, 0x6c,
	0xf7, 0x5c, 0xed, 0x0d, 0x88, 0xf2, 0x00, 0x6d, 0x41, 0xd9, 0xb1, 0x54, 0xbd, 0x47, 0x2c, 0x5b,
	0xc9, 0x34, 0x4d, 0x78, 0xb8, 0x79, 0x7f, 0xe8, 0x10, 0x0e, 0x64, 0xb2, 0x4b, 0xd7, 0x22, 0x3f,
	0x0c, 0x88, 0xed, 0x10, 0xcd, 0xbd, 0xd0, 0x9d, 0xee, 0x2a, 0x15, 0x82, 0xda, 0x65, 0xbf, 0xc7,
	0x66, 0x55, 0x12, 0x94, 0x4c, 0xf3, 0x35, 0x54, 0x56, 0xdb, 0x44, 0xfb, 0xa0, 0xc8, 0x1c, 0x1c,
	0xbb, 0x53, 0xa0, 0xe9, 0xb6, 0x7a, 0xd2, 0x23, 0x9a, 0x92, 0x41, 0x55, 0x28, 0x11, 0x43, 0x18,
	0xd9, 0x93, 0x12, 0x14, 0x78, 0x39, 0x9a, 0x11, 0x14, 0xe5, 0x8d, 0xb8, 0x0b, 0xdb, 0x32, 0x47,
	0x9f, 0x38, 0x5d, 0x53, 0x53, 0x1e, 0xa0, 0x12, 0xe4, 0xde, 0x10, 0x47, 0xc9, 0xa0, 0x32, 0xe4,
	0xbb, 0x44, 0xd5, 0x94, 0x2c, 0x5b, 0x9d, 0x99, 0xb6, 0xa3, 0xe4, 0x98, 0xf3, 0x6c, 0xe0, 0x28,
	0x79, 0x04, 0x50, 0xd4, 0x48, 0x8f, 0x38, 0x44, 0x29, 0xb0, 0x8f, 0x74, 0x4c, 0xc3, 0x20, 0x1d,
	0x47, 0x29, 0x32, 0xc3, 0x3c, 0x73, 0x74, 0xd3, 0xb0, 0x95, 0x12, 0xaa, 0x40, 0xc1, 0xb1, 0xd4,
	0x0e, 0x51, 0xca, 0xcd, 0x3f, 0x73, 0x50, 0xb6, 0x68, 0xbc, 0x08, 0x83, 0x98, 0x3d, 0x19, 0xf9,
	0x4e, 0x38, 0xa6, 0x1f, 0x3d, 0x9c, 0xc2, 0xd9, 0x62, 0x9e, 0xd8, 0xe2, 0x84, 0xfa, 0xaf, 0xb9,
	0xbb, 0xf7, 0xec, 0x3b, 0x78, 0xf2, 0xd1, 0xed, 0xad, 0x5e, 0x5d, 0x85, 0xd7, 0xae, 0x18, 0xcf,
	0x58, 0xbe, 0x72, 0x8f, 0xd6, 0x6e, 0x69, 0xce, 0x90, 0x04, 0xf4, 0x4b, 0x06, 0x1a, 0x1b, 0x33,
	0x74, 0x22, 0x3a, 0xa6, 0x41, 0xe2, 0x7b, 0x57, 0x31, 0xef, 0x86, 0x5a, 0xfb, 0xf5, 0xba, 0xa4,
	0xb4, 0xc7, 0xbe, 0x14, 0x2d, 0x1b, 0xf0, 0xe0, 0x53, 0x0d, 0xf7, 0x48, 0x48, 0xfd, 0xe4, 0x79,
	0x23, 0x37, 0x8b, 0x30, 0xa6, 0xab, 0x57, 0x28, 0xc7, 0x27, 0x6d, 0xfd, 0x25, 0x13, 0x14, 0xc9,
	0x68, 0x2e, 0xe0, 0x7f, 0xff, 0x4c, 0x0b, 0xfa, 0x1a, 0x5e, 0xca, 0x13, 0x56, 0x3b, 0x1d, 0x62,
	0xdb, 0x6e, 0xc7, 0x34, 0x1c, 0xcb, 0xec, 0xb9, 0x6a, 0xaf, 0x67, 0x5e, 0xb8, 0x1d, 0x8b, 0x68,
	0xc4, 0x70, 0x74, 0xb5, 0x77, 0xd7, 0xc4, 0x15, 0x28, 0x9c, 0xaa, 0x3d, 0x9b, 0x88, 0x1e, 0x70,
	0xac, 0x01, 0x51, 0xb2, 0xcd, 0x43, 0x28, 0xf0, 0x83, 0x41, 0x3b, 0x50, 0x95, 0x09, 0x3b, 0xa6,
	0x46, 0x78, 0xc3, 0x64, 0xcd, 0xb7, 0xca, 0x1f, 0x99, 0x93, 0xc3, 0x9f, 0x9e, 0x4d, 0xfd, 0x64,
	0xb6, 0x1c, 0xb6, 0x46, 0xe1, 0xfc, 0xf8, 0x43, 0x4c, 0xdf, 0xcd, 0xbc, 0x48, 0xfc, 0x7f, 0x5d,
	0xd3, 0xe1, 0xf1, 0x35, 0x1d, 0x0e, 0x8b, 0xdc, 0x7a, 0xf5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xd3, 0xc9, 0x49, 0x43, 0xad, 0x09, 0x00, 0x00,
}
